/*
* generated by Xtext
*/

package org.fornax.soa.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.fornax.soa.basedsl.services.SOABaseDslGrammarAccess;

@Singleton
public class SolutionDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Assignment cSolutionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSolutionSolutionParserRuleCall_1_0 = (RuleCall)cSolutionAssignment_1.eContents().get(0);
		
		//Model:
		//	imports+=Import* solution+=Solution*;
		public ParserRule getRule() { return rule; }

		//imports+=Import* solution+=Solution*
		public Group getGroup() { return cGroup; }

		//imports+=Import*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }

		//Import
		public RuleCall getImportsImportParserRuleCall_0_0() { return cImportsImportParserRuleCall_0_0; }

		//solution+=Solution*
		public Assignment getSolutionAssignment_1() { return cSolutionAssignment_1; }

		//Solution
		public RuleCall getSolutionSolutionParserRuleCall_1_0() { return cSolutionSolutionParserRuleCall_1_0; }
	}

	public class SolutionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Solution");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSolutionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDomainKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDomainAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cDomainDomainCrossReference_3_1_0 = (CrossReference)cDomainAssignment_3_1.eContents().get(0);
		private final RuleCall cDomainDomainQualifiedNameParserRuleCall_3_1_0_1 = (RuleCall)cDomainDomainCrossReference_3_1_0.eContents().get(1);
		private final Assignment cVersionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVersionVersionParserRuleCall_4_0 = (RuleCall)cVersionAssignment_4.eContents().get(0);
		private final Keyword cLifecycleStateKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStateAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cStateLifecycleStateCrossReference_6_0 = (CrossReference)cStateAssignment_6.eContents().get(0);
		private final RuleCall cStateLifecycleStateQualifiedNameParserRuleCall_6_0_1 = (RuleCall)cStateLifecycleStateCrossReference_6_0.eContents().get(1);
		private final Assignment cProductVersionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cProductVersionProductVersionParserRuleCall_7_0 = (RuleCall)cProductVersionAssignment_7.eContents().get(0);
		private final Assignment cAdditionalInfoAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cAdditionalInfoAdditionalInformationParserRuleCall_8_0 = (RuleCall)cAdditionalInfoAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cRequiresKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cRequiresAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cRequiresServiceRefParserRuleCall_9_1_0 = (RuleCall)cRequiresAssignment_9_1.eContents().get(0);
		private final Assignment cFeaturesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cFeaturesFeatureParserRuleCall_10_0 = (RuleCall)cFeaturesAssignment_10.eContents().get(0);
		private final Assignment cModulesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cModulesModuleParserRuleCall_11_0 = (RuleCall)cModulesAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cContactsKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Group cGroup_12_2 = (Group)cGroup_12.eContents().get(2);
		private final Keyword cOwnerKeyword_12_2_0 = (Keyword)cGroup_12_2.eContents().get(0);
		private final Assignment cOwnerAssignment_12_2_1 = (Assignment)cGroup_12_2.eContents().get(1);
		private final CrossReference cOwnerUserCrossReference_12_2_1_0 = (CrossReference)cOwnerAssignment_12_2_1.eContents().get(0);
		private final RuleCall cOwnerUserQualifiedNameParserRuleCall_12_2_1_0_1 = (RuleCall)cOwnerUserCrossReference_12_2_1_0.eContents().get(1);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cResponsibleKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cResponsibleAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final CrossReference cResponsibleUserCrossReference_12_3_1_0 = (CrossReference)cResponsibleAssignment_12_3_1.eContents().get(0);
		private final RuleCall cResponsibleUserQualifiedNameParserRuleCall_12_3_1_0_1 = (RuleCall)cResponsibleUserCrossReference_12_3_1_0.eContents().get(1);
		private final Group cGroup_12_4 = (Group)cGroup_12.eContents().get(4);
		private final Keyword cBudgetingKeyword_12_4_0 = (Keyword)cGroup_12_4.eContents().get(0);
		private final Assignment cBudgetingAssignment_12_4_1 = (Assignment)cGroup_12_4.eContents().get(1);
		private final CrossReference cBudgetingUserCrossReference_12_4_1_0 = (CrossReference)cBudgetingAssignment_12_4_1.eContents().get(0);
		private final RuleCall cBudgetingUserQualifiedNameParserRuleCall_12_4_1_0_1 = (RuleCall)cBudgetingUserCrossReference_12_4_1_0.eContents().get(1);
		private final Group cGroup_12_5 = (Group)cGroup_12.eContents().get(5);
		private final Keyword cSubscriptionsKeyword_12_5_0 = (Keyword)cGroup_12_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_5_1 = (Keyword)cGroup_12_5.eContents().get(1);
		private final Assignment cSubscriptionsAssignment_12_5_2 = (Assignment)cGroup_12_5.eContents().get(2);
		private final CrossReference cSubscriptionsUserCrossReference_12_5_2_0 = (CrossReference)cSubscriptionsAssignment_12_5_2.eContents().get(0);
		private final RuleCall cSubscriptionsUserQualifiedNameParserRuleCall_12_5_2_0_1 = (RuleCall)cSubscriptionsUserCrossReference_12_5_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12_5_3 = (Keyword)cGroup_12_5.eContents().get(3);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cTagsKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cTagsAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final CrossReference cTagsTagCrossReference_13_1_0 = (CrossReference)cTagsAssignment_13_1.eContents().get(0);
		private final RuleCall cTagsTagIDTerminalRuleCall_13_1_0_1 = (RuleCall)cTagsTagCrossReference_13_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Solution:
		//	"solution" name=QualifiedName "{" ("domain" domain=[businessDsl::Domain|QualifiedName])? version=Version
		//	"lifecycle-state" state=[profileDsl::LifecycleState|QualifiedName] productVersion=ProductVersion?
		//	additionalInfo=AdditionalInformation? ("requires" requires+=ServiceRef)* features+=Feature* modules+=Module*
		//	("contacts" "{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible"
		//	responsible+=[basedsl::User|QualifiedName])* ("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions"
		//	"{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)? ("tags" tags+=[semanticsDsl::Tag]+)? "}";
		public ParserRule getRule() { return rule; }

		//"solution" name=QualifiedName "{" ("domain" domain=[businessDsl::Domain|QualifiedName])? version=Version
		//"lifecycle-state" state=[profileDsl::LifecycleState|QualifiedName] productVersion=ProductVersion?
		//additionalInfo=AdditionalInformation? ("requires" requires+=ServiceRef)* features+=Feature* modules+=Module*
		//("contacts" "{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible"
		//responsible+=[basedsl::User|QualifiedName])* ("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions"
		//"{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)? ("tags" tags+=[semanticsDsl::Tag]+)? "}"
		public Group getGroup() { return cGroup; }

		//"solution"
		public Keyword getSolutionKeyword_0() { return cSolutionKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("domain" domain=[businessDsl::Domain|QualifiedName])?
		public Group getGroup_3() { return cGroup_3; }

		//"domain"
		public Keyword getDomainKeyword_3_0() { return cDomainKeyword_3_0; }

		//domain=[businessDsl::Domain|QualifiedName]
		public Assignment getDomainAssignment_3_1() { return cDomainAssignment_3_1; }

		//[businessDsl::Domain|QualifiedName]
		public CrossReference getDomainDomainCrossReference_3_1_0() { return cDomainDomainCrossReference_3_1_0; }

		//QualifiedName
		public RuleCall getDomainDomainQualifiedNameParserRuleCall_3_1_0_1() { return cDomainDomainQualifiedNameParserRuleCall_3_1_0_1; }

		//version=Version
		public Assignment getVersionAssignment_4() { return cVersionAssignment_4; }

		//Version
		public RuleCall getVersionVersionParserRuleCall_4_0() { return cVersionVersionParserRuleCall_4_0; }

		//"lifecycle-state"
		public Keyword getLifecycleStateKeyword_5() { return cLifecycleStateKeyword_5; }

		//state=[profileDsl::LifecycleState|QualifiedName]
		public Assignment getStateAssignment_6() { return cStateAssignment_6; }

		//[profileDsl::LifecycleState|QualifiedName]
		public CrossReference getStateLifecycleStateCrossReference_6_0() { return cStateLifecycleStateCrossReference_6_0; }

		//QualifiedName
		public RuleCall getStateLifecycleStateQualifiedNameParserRuleCall_6_0_1() { return cStateLifecycleStateQualifiedNameParserRuleCall_6_0_1; }

		//productVersion=ProductVersion?
		public Assignment getProductVersionAssignment_7() { return cProductVersionAssignment_7; }

		//ProductVersion
		public RuleCall getProductVersionProductVersionParserRuleCall_7_0() { return cProductVersionProductVersionParserRuleCall_7_0; }

		//additionalInfo=AdditionalInformation?
		public Assignment getAdditionalInfoAssignment_8() { return cAdditionalInfoAssignment_8; }

		//AdditionalInformation
		public RuleCall getAdditionalInfoAdditionalInformationParserRuleCall_8_0() { return cAdditionalInfoAdditionalInformationParserRuleCall_8_0; }

		//("requires" requires+=ServiceRef)*
		public Group getGroup_9() { return cGroup_9; }

		//"requires"
		public Keyword getRequiresKeyword_9_0() { return cRequiresKeyword_9_0; }

		//requires+=ServiceRef
		public Assignment getRequiresAssignment_9_1() { return cRequiresAssignment_9_1; }

		//ServiceRef
		public RuleCall getRequiresServiceRefParserRuleCall_9_1_0() { return cRequiresServiceRefParserRuleCall_9_1_0; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_10() { return cFeaturesAssignment_10; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_10_0() { return cFeaturesFeatureParserRuleCall_10_0; }

		//modules+=Module*
		public Assignment getModulesAssignment_11() { return cModulesAssignment_11; }

		//Module
		public RuleCall getModulesModuleParserRuleCall_11_0() { return cModulesModuleParserRuleCall_11_0; }

		//("contacts" "{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible"
		//responsible+=[basedsl::User|QualifiedName])* ("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions"
		//"{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)?
		public Group getGroup_12() { return cGroup_12; }

		//"contacts"
		public Keyword getContactsKeyword_12_0() { return cContactsKeyword_12_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }

		//("owner" owner=[basedsl::User|QualifiedName])?
		public Group getGroup_12_2() { return cGroup_12_2; }

		//"owner"
		public Keyword getOwnerKeyword_12_2_0() { return cOwnerKeyword_12_2_0; }

		//owner=[basedsl::User|QualifiedName]
		public Assignment getOwnerAssignment_12_2_1() { return cOwnerAssignment_12_2_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getOwnerUserCrossReference_12_2_1_0() { return cOwnerUserCrossReference_12_2_1_0; }

		//QualifiedName
		public RuleCall getOwnerUserQualifiedNameParserRuleCall_12_2_1_0_1() { return cOwnerUserQualifiedNameParserRuleCall_12_2_1_0_1; }

		//("responsible" responsible+=[basedsl::User|QualifiedName])*
		public Group getGroup_12_3() { return cGroup_12_3; }

		//"responsible"
		public Keyword getResponsibleKeyword_12_3_0() { return cResponsibleKeyword_12_3_0; }

		//responsible+=[basedsl::User|QualifiedName]
		public Assignment getResponsibleAssignment_12_3_1() { return cResponsibleAssignment_12_3_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getResponsibleUserCrossReference_12_3_1_0() { return cResponsibleUserCrossReference_12_3_1_0; }

		//QualifiedName
		public RuleCall getResponsibleUserQualifiedNameParserRuleCall_12_3_1_0_1() { return cResponsibleUserQualifiedNameParserRuleCall_12_3_1_0_1; }

		//("budgeting" budgeting=[basedsl::User|QualifiedName])?
		public Group getGroup_12_4() { return cGroup_12_4; }

		//"budgeting"
		public Keyword getBudgetingKeyword_12_4_0() { return cBudgetingKeyword_12_4_0; }

		//budgeting=[basedsl::User|QualifiedName]
		public Assignment getBudgetingAssignment_12_4_1() { return cBudgetingAssignment_12_4_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getBudgetingUserCrossReference_12_4_1_0() { return cBudgetingUserCrossReference_12_4_1_0; }

		//QualifiedName
		public RuleCall getBudgetingUserQualifiedNameParserRuleCall_12_4_1_0_1() { return cBudgetingUserQualifiedNameParserRuleCall_12_4_1_0_1; }

		//("subscriptions" "{" subscriptions+=[basedsl::User|QualifiedName]* "}")?
		public Group getGroup_12_5() { return cGroup_12_5; }

		//"subscriptions"
		public Keyword getSubscriptionsKeyword_12_5_0() { return cSubscriptionsKeyword_12_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_12_5_1() { return cLeftCurlyBracketKeyword_12_5_1; }

		//subscriptions+=[basedsl::User|QualifiedName]*
		public Assignment getSubscriptionsAssignment_12_5_2() { return cSubscriptionsAssignment_12_5_2; }

		//[basedsl::User|QualifiedName]
		public CrossReference getSubscriptionsUserCrossReference_12_5_2_0() { return cSubscriptionsUserCrossReference_12_5_2_0; }

		//QualifiedName
		public RuleCall getSubscriptionsUserQualifiedNameParserRuleCall_12_5_2_0_1() { return cSubscriptionsUserQualifiedNameParserRuleCall_12_5_2_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12_5_3() { return cRightCurlyBracketKeyword_12_5_3; }

		//("tags" tags+=[semanticsDsl::Tag]+)?
		public Group getGroup_13() { return cGroup_13; }

		//"tags"
		public Keyword getTagsKeyword_13_0() { return cTagsKeyword_13_0; }

		//tags+=[semanticsDsl::Tag]+
		public Assignment getTagsAssignment_13_1() { return cTagsAssignment_13_1; }

		//[semanticsDsl::Tag]
		public CrossReference getTagsTagCrossReference_13_1_0() { return cTagsTagCrossReference_13_1_0; }

		//ID
		public RuleCall getTagsTagIDTerminalRuleCall_13_1_0_1() { return cTagsTagIDTerminalRuleCall_13_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class ModuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Module");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cKindKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cKindAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cKindModuleKindEnumRuleCall_4_0 = (RuleCall)cKindAssignment_4.eContents().get(0);
		private final Assignment cVersionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cVersionVersionParserRuleCall_5_0 = (RuleCall)cVersionAssignment_5.eContents().get(0);
		private final Assignment cAdditionalInfoAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAdditionalInfoAdditionalInformationParserRuleCall_6_0 = (RuleCall)cAdditionalInfoAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRequiresKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cRequiresAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cRequiresServiceRefParserRuleCall_7_1_0 = (RuleCall)cRequiresAssignment_7_1.eContents().get(0);
		private final Assignment cFeaturesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cFeaturesFeatureParserRuleCall_8_0 = (RuleCall)cFeaturesAssignment_8.eContents().get(0);
		private final Assignment cModulesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cModulesModuleParserRuleCall_9_0 = (RuleCall)cModulesAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cContactsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cOwnerKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Assignment cOwnerAssignment_10_2_1 = (Assignment)cGroup_10_2.eContents().get(1);
		private final CrossReference cOwnerUserCrossReference_10_2_1_0 = (CrossReference)cOwnerAssignment_10_2_1.eContents().get(0);
		private final RuleCall cOwnerUserQualifiedNameParserRuleCall_10_2_1_0_1 = (RuleCall)cOwnerUserCrossReference_10_2_1_0.eContents().get(1);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cResponsibleKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cResponsibleAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final CrossReference cResponsibleUserCrossReference_10_3_1_0 = (CrossReference)cResponsibleAssignment_10_3_1.eContents().get(0);
		private final RuleCall cResponsibleUserQualifiedNameParserRuleCall_10_3_1_0_1 = (RuleCall)cResponsibleUserCrossReference_10_3_1_0.eContents().get(1);
		private final Group cGroup_10_4 = (Group)cGroup_10.eContents().get(4);
		private final Keyword cBudgetingKeyword_10_4_0 = (Keyword)cGroup_10_4.eContents().get(0);
		private final Assignment cBudgetingAssignment_10_4_1 = (Assignment)cGroup_10_4.eContents().get(1);
		private final CrossReference cBudgetingUserCrossReference_10_4_1_0 = (CrossReference)cBudgetingAssignment_10_4_1.eContents().get(0);
		private final RuleCall cBudgetingUserQualifiedNameParserRuleCall_10_4_1_0_1 = (RuleCall)cBudgetingUserCrossReference_10_4_1_0.eContents().get(1);
		private final Group cGroup_10_5 = (Group)cGroup_10.eContents().get(5);
		private final Keyword cSubscriptionsKeyword_10_5_0 = (Keyword)cGroup_10_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_5_1 = (Keyword)cGroup_10_5.eContents().get(1);
		private final Assignment cSubscriptionsAssignment_10_5_2 = (Assignment)cGroup_10_5.eContents().get(2);
		private final CrossReference cSubscriptionsUserCrossReference_10_5_2_0 = (CrossReference)cSubscriptionsAssignment_10_5_2.eContents().get(0);
		private final RuleCall cSubscriptionsUserQualifiedNameParserRuleCall_10_5_2_0_1 = (RuleCall)cSubscriptionsUserCrossReference_10_5_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10_5_3 = (Keyword)cGroup_10_5.eContents().get(3);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cTagsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cTagsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cTagsTagCrossReference_11_1_0 = (CrossReference)cTagsAssignment_11_1.eContents().get(0);
		private final RuleCall cTagsTagIDTerminalRuleCall_11_1_0_1 = (RuleCall)cTagsTagCrossReference_11_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Module:
		//	"module" name=ID "{" "kind" kind=ModuleKind version=Version? additionalInfo=AdditionalInformation? ("requires"
		//	requires+=ServiceRef)* features+=Feature* modules+=Module* ("contacts" "{" ("owner"
		//	owner=[basedsl::User|QualifiedName])? ("responsible" responsible+=[basedsl::User|QualifiedName])* ("budgeting"
		//	budgeting=[basedsl::User|QualifiedName])? ("subscriptions" "{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)?
		//	("tags" tags+=[semanticsDsl::Tag]+)? "}";
		public ParserRule getRule() { return rule; }

		//"module" name=ID "{" "kind" kind=ModuleKind version=Version? additionalInfo=AdditionalInformation? ("requires"
		//requires+=ServiceRef)* features+=Feature* modules+=Module* ("contacts" "{" ("owner"
		//owner=[basedsl::User|QualifiedName])? ("responsible" responsible+=[basedsl::User|QualifiedName])* ("budgeting"
		//budgeting=[basedsl::User|QualifiedName])? ("subscriptions" "{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)?
		//("tags" tags+=[semanticsDsl::Tag]+)? "}"
		public Group getGroup() { return cGroup; }

		//"module"
		public Keyword getModuleKeyword_0() { return cModuleKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"kind"
		public Keyword getKindKeyword_3() { return cKindKeyword_3; }

		//kind=ModuleKind
		public Assignment getKindAssignment_4() { return cKindAssignment_4; }

		//ModuleKind
		public RuleCall getKindModuleKindEnumRuleCall_4_0() { return cKindModuleKindEnumRuleCall_4_0; }

		//version=Version?
		public Assignment getVersionAssignment_5() { return cVersionAssignment_5; }

		//Version
		public RuleCall getVersionVersionParserRuleCall_5_0() { return cVersionVersionParserRuleCall_5_0; }

		//additionalInfo=AdditionalInformation?
		public Assignment getAdditionalInfoAssignment_6() { return cAdditionalInfoAssignment_6; }

		//AdditionalInformation
		public RuleCall getAdditionalInfoAdditionalInformationParserRuleCall_6_0() { return cAdditionalInfoAdditionalInformationParserRuleCall_6_0; }

		//("requires" requires+=ServiceRef)*
		public Group getGroup_7() { return cGroup_7; }

		//"requires"
		public Keyword getRequiresKeyword_7_0() { return cRequiresKeyword_7_0; }

		//requires+=ServiceRef
		public Assignment getRequiresAssignment_7_1() { return cRequiresAssignment_7_1; }

		//ServiceRef
		public RuleCall getRequiresServiceRefParserRuleCall_7_1_0() { return cRequiresServiceRefParserRuleCall_7_1_0; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_8() { return cFeaturesAssignment_8; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_8_0() { return cFeaturesFeatureParserRuleCall_8_0; }

		//modules+=Module*
		public Assignment getModulesAssignment_9() { return cModulesAssignment_9; }

		//Module
		public RuleCall getModulesModuleParserRuleCall_9_0() { return cModulesModuleParserRuleCall_9_0; }

		//("contacts" "{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible"
		//responsible+=[basedsl::User|QualifiedName])* ("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions"
		//"{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)?
		public Group getGroup_10() { return cGroup_10; }

		//"contacts"
		public Keyword getContactsKeyword_10_0() { return cContactsKeyword_10_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }

		//("owner" owner=[basedsl::User|QualifiedName])?
		public Group getGroup_10_2() { return cGroup_10_2; }

		//"owner"
		public Keyword getOwnerKeyword_10_2_0() { return cOwnerKeyword_10_2_0; }

		//owner=[basedsl::User|QualifiedName]
		public Assignment getOwnerAssignment_10_2_1() { return cOwnerAssignment_10_2_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getOwnerUserCrossReference_10_2_1_0() { return cOwnerUserCrossReference_10_2_1_0; }

		//QualifiedName
		public RuleCall getOwnerUserQualifiedNameParserRuleCall_10_2_1_0_1() { return cOwnerUserQualifiedNameParserRuleCall_10_2_1_0_1; }

		//("responsible" responsible+=[basedsl::User|QualifiedName])*
		public Group getGroup_10_3() { return cGroup_10_3; }

		//"responsible"
		public Keyword getResponsibleKeyword_10_3_0() { return cResponsibleKeyword_10_3_0; }

		//responsible+=[basedsl::User|QualifiedName]
		public Assignment getResponsibleAssignment_10_3_1() { return cResponsibleAssignment_10_3_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getResponsibleUserCrossReference_10_3_1_0() { return cResponsibleUserCrossReference_10_3_1_0; }

		//QualifiedName
		public RuleCall getResponsibleUserQualifiedNameParserRuleCall_10_3_1_0_1() { return cResponsibleUserQualifiedNameParserRuleCall_10_3_1_0_1; }

		//("budgeting" budgeting=[basedsl::User|QualifiedName])?
		public Group getGroup_10_4() { return cGroup_10_4; }

		//"budgeting"
		public Keyword getBudgetingKeyword_10_4_0() { return cBudgetingKeyword_10_4_0; }

		//budgeting=[basedsl::User|QualifiedName]
		public Assignment getBudgetingAssignment_10_4_1() { return cBudgetingAssignment_10_4_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getBudgetingUserCrossReference_10_4_1_0() { return cBudgetingUserCrossReference_10_4_1_0; }

		//QualifiedName
		public RuleCall getBudgetingUserQualifiedNameParserRuleCall_10_4_1_0_1() { return cBudgetingUserQualifiedNameParserRuleCall_10_4_1_0_1; }

		//("subscriptions" "{" subscriptions+=[basedsl::User|QualifiedName]* "}")?
		public Group getGroup_10_5() { return cGroup_10_5; }

		//"subscriptions"
		public Keyword getSubscriptionsKeyword_10_5_0() { return cSubscriptionsKeyword_10_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_5_1() { return cLeftCurlyBracketKeyword_10_5_1; }

		//subscriptions+=[basedsl::User|QualifiedName]*
		public Assignment getSubscriptionsAssignment_10_5_2() { return cSubscriptionsAssignment_10_5_2; }

		//[basedsl::User|QualifiedName]
		public CrossReference getSubscriptionsUserCrossReference_10_5_2_0() { return cSubscriptionsUserCrossReference_10_5_2_0; }

		//QualifiedName
		public RuleCall getSubscriptionsUserQualifiedNameParserRuleCall_10_5_2_0_1() { return cSubscriptionsUserQualifiedNameParserRuleCall_10_5_2_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10_5_3() { return cRightCurlyBracketKeyword_10_5_3; }

		//("tags" tags+=[semanticsDsl::Tag]+)?
		public Group getGroup_11() { return cGroup_11; }

		//"tags"
		public Keyword getTagsKeyword_11_0() { return cTagsKeyword_11_0; }

		//tags+=[semanticsDsl::Tag]+
		public Assignment getTagsAssignment_11_1() { return cTagsAssignment_11_1; }

		//[semanticsDsl::Tag]
		public CrossReference getTagsTagCrossReference_11_1_0() { return cTagsTagCrossReference_11_1_0; }

		//ID
		public RuleCall getTagsTagIDTerminalRuleCall_11_1_0_1() { return cTagsTagIDTerminalRuleCall_11_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNonFunctionalAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNonFunctionalNonFunctionalKeyword_0_0 = (Keyword)cNonFunctionalAssignment_0.eContents().get(0);
		private final Keyword cFeatureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUseCasesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUseCaseAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUseCaseSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cUseCaseAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Assignment cAdditionalInfoAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAdditionalInfoAdditionalInformationParserRuleCall_6_0 = (RuleCall)cAdditionalInfoAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cUsesCapabilitiesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cUsesCapabilitiesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cUsesCapabilitiesCapabilityRefParserRuleCall_7_2_0 = (RuleCall)cUsesCapabilitiesAssignment_7_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cRequiresKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cRequiresAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cRequiresServiceRefParserRuleCall_8_1_0 = (RuleCall)cRequiresAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSubscribesToEventKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cEventAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cEventEventRefParserRuleCall_9_1_0 = (RuleCall)cEventAssignment_9_1.eContents().get(0);
		private final Group cGroup_9_2 = (Group)cGroup_9.eContents().get(2);
		private final Keyword cCommaKeyword_9_2_0 = (Keyword)cGroup_9_2.eContents().get(0);
		private final Assignment cEventAssignment_9_2_1 = (Assignment)cGroup_9_2.eContents().get(1);
		private final RuleCall cEventEventRefParserRuleCall_9_2_1_0 = (RuleCall)cEventAssignment_9_2_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cContactsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cOwnerKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Assignment cOwnerAssignment_10_2_1 = (Assignment)cGroup_10_2.eContents().get(1);
		private final CrossReference cOwnerUserCrossReference_10_2_1_0 = (CrossReference)cOwnerAssignment_10_2_1.eContents().get(0);
		private final RuleCall cOwnerUserQualifiedNameParserRuleCall_10_2_1_0_1 = (RuleCall)cOwnerUserCrossReference_10_2_1_0.eContents().get(1);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cResponsibleKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cResponsibleAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final CrossReference cResponsibleUserCrossReference_10_3_1_0 = (CrossReference)cResponsibleAssignment_10_3_1.eContents().get(0);
		private final RuleCall cResponsibleUserQualifiedNameParserRuleCall_10_3_1_0_1 = (RuleCall)cResponsibleUserCrossReference_10_3_1_0.eContents().get(1);
		private final Group cGroup_10_4 = (Group)cGroup_10.eContents().get(4);
		private final Keyword cBudgetingKeyword_10_4_0 = (Keyword)cGroup_10_4.eContents().get(0);
		private final Assignment cBudgetingAssignment_10_4_1 = (Assignment)cGroup_10_4.eContents().get(1);
		private final CrossReference cBudgetingUserCrossReference_10_4_1_0 = (CrossReference)cBudgetingAssignment_10_4_1.eContents().get(0);
		private final RuleCall cBudgetingUserQualifiedNameParserRuleCall_10_4_1_0_1 = (RuleCall)cBudgetingUserCrossReference_10_4_1_0.eContents().get(1);
		private final Group cGroup_10_5 = (Group)cGroup_10.eContents().get(5);
		private final Keyword cSubscriptionsKeyword_10_5_0 = (Keyword)cGroup_10_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_5_1 = (Keyword)cGroup_10_5.eContents().get(1);
		private final Assignment cSubscriptionsAssignment_10_5_2 = (Assignment)cGroup_10_5.eContents().get(2);
		private final CrossReference cSubscriptionsUserCrossReference_10_5_2_0 = (CrossReference)cSubscriptionsAssignment_10_5_2.eContents().get(0);
		private final RuleCall cSubscriptionsUserQualifiedNameParserRuleCall_10_5_2_0_1 = (RuleCall)cSubscriptionsUserCrossReference_10_5_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10_5_3 = (Keyword)cGroup_10_5.eContents().get(3);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cTagsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cTagsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cTagsTagCrossReference_11_1_0 = (CrossReference)cTagsAssignment_11_1.eContents().get(0);
		private final RuleCall cTagsTagIDTerminalRuleCall_11_1_0_1 = (RuleCall)cTagsTagCrossReference_11_1_0.eContents().get(1);
		private final Assignment cFeaturesAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cFeaturesFeatureParserRuleCall_12_0 = (RuleCall)cFeaturesAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Feature:
		//	nonFunctional?="non-functional"? "feature" name=ID "{" ("use-cases" useCase+=STRING+)? ("description"
		//	description=STRING)? additionalInfo=AdditionalInformation? ("uses-capabilities" "{" usesCapabilities+=CapabilityRef+
		//	"}")? ("requires" requires+=ServiceRef)* ("subscribes-to-event" event+=EventRef ("," event+=EventRef)*)? ("contacts"
		//	"{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible" responsible+=[basedsl::User|QualifiedName])*
		//	("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions" "{"
		//	subscriptions+=[basedsl::User|QualifiedName]* "}")?)? ("tags" tags+=[semanticsDsl::Tag]+)? features+=Feature* "}";
		public ParserRule getRule() { return rule; }

		//nonFunctional?="non-functional"? "feature" name=ID "{" ("use-cases" useCase+=STRING+)? ("description"
		//description=STRING)? additionalInfo=AdditionalInformation? ("uses-capabilities" "{" usesCapabilities+=CapabilityRef+
		//"}")? ("requires" requires+=ServiceRef)* ("subscribes-to-event" event+=EventRef ("," event+=EventRef)*)? ("contacts"
		//"{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible" responsible+=[basedsl::User|QualifiedName])*
		//("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions" "{"
		//subscriptions+=[basedsl::User|QualifiedName]* "}")?)? ("tags" tags+=[semanticsDsl::Tag]+)? features+=Feature* "}"
		public Group getGroup() { return cGroup; }

		//nonFunctional?="non-functional"?
		public Assignment getNonFunctionalAssignment_0() { return cNonFunctionalAssignment_0; }

		//"non-functional"
		public Keyword getNonFunctionalNonFunctionalKeyword_0_0() { return cNonFunctionalNonFunctionalKeyword_0_0; }

		//"feature"
		public Keyword getFeatureKeyword_1() { return cFeatureKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("use-cases" useCase+=STRING+)?
		public Group getGroup_4() { return cGroup_4; }

		//"use-cases"
		public Keyword getUseCasesKeyword_4_0() { return cUseCasesKeyword_4_0; }

		//useCase+=STRING+
		public Assignment getUseCaseAssignment_4_1() { return cUseCaseAssignment_4_1; }

		//STRING
		public RuleCall getUseCaseSTRINGTerminalRuleCall_4_1_0() { return cUseCaseSTRINGTerminalRuleCall_4_1_0; }

		//("description" description=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"description"
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_1_0() { return cDescriptionSTRINGTerminalRuleCall_5_1_0; }

		//additionalInfo=AdditionalInformation?
		public Assignment getAdditionalInfoAssignment_6() { return cAdditionalInfoAssignment_6; }

		//AdditionalInformation
		public RuleCall getAdditionalInfoAdditionalInformationParserRuleCall_6_0() { return cAdditionalInfoAdditionalInformationParserRuleCall_6_0; }

		//("uses-capabilities" "{" usesCapabilities+=CapabilityRef+ "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"uses-capabilities"
		public Keyword getUsesCapabilitiesKeyword_7_0() { return cUsesCapabilitiesKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//usesCapabilities+=CapabilityRef+
		public Assignment getUsesCapabilitiesAssignment_7_2() { return cUsesCapabilitiesAssignment_7_2; }

		//CapabilityRef
		public RuleCall getUsesCapabilitiesCapabilityRefParserRuleCall_7_2_0() { return cUsesCapabilitiesCapabilityRefParserRuleCall_7_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }

		//("requires" requires+=ServiceRef)*
		public Group getGroup_8() { return cGroup_8; }

		//"requires"
		public Keyword getRequiresKeyword_8_0() { return cRequiresKeyword_8_0; }

		//requires+=ServiceRef
		public Assignment getRequiresAssignment_8_1() { return cRequiresAssignment_8_1; }

		//ServiceRef
		public RuleCall getRequiresServiceRefParserRuleCall_8_1_0() { return cRequiresServiceRefParserRuleCall_8_1_0; }

		//("subscribes-to-event" event+=EventRef ("," event+=EventRef)*)?
		public Group getGroup_9() { return cGroup_9; }

		//"subscribes-to-event"
		public Keyword getSubscribesToEventKeyword_9_0() { return cSubscribesToEventKeyword_9_0; }

		//event+=EventRef
		public Assignment getEventAssignment_9_1() { return cEventAssignment_9_1; }

		//EventRef
		public RuleCall getEventEventRefParserRuleCall_9_1_0() { return cEventEventRefParserRuleCall_9_1_0; }

		//("," event+=EventRef)*
		public Group getGroup_9_2() { return cGroup_9_2; }

		//","
		public Keyword getCommaKeyword_9_2_0() { return cCommaKeyword_9_2_0; }

		//event+=EventRef
		public Assignment getEventAssignment_9_2_1() { return cEventAssignment_9_2_1; }

		//EventRef
		public RuleCall getEventEventRefParserRuleCall_9_2_1_0() { return cEventEventRefParserRuleCall_9_2_1_0; }

		//("contacts" "{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible"
		//responsible+=[basedsl::User|QualifiedName])* ("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions"
		//"{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)?
		public Group getGroup_10() { return cGroup_10; }

		//"contacts"
		public Keyword getContactsKeyword_10_0() { return cContactsKeyword_10_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }

		//("owner" owner=[basedsl::User|QualifiedName])?
		public Group getGroup_10_2() { return cGroup_10_2; }

		//"owner"
		public Keyword getOwnerKeyword_10_2_0() { return cOwnerKeyword_10_2_0; }

		//owner=[basedsl::User|QualifiedName]
		public Assignment getOwnerAssignment_10_2_1() { return cOwnerAssignment_10_2_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getOwnerUserCrossReference_10_2_1_0() { return cOwnerUserCrossReference_10_2_1_0; }

		//QualifiedName
		public RuleCall getOwnerUserQualifiedNameParserRuleCall_10_2_1_0_1() { return cOwnerUserQualifiedNameParserRuleCall_10_2_1_0_1; }

		//("responsible" responsible+=[basedsl::User|QualifiedName])*
		public Group getGroup_10_3() { return cGroup_10_3; }

		//"responsible"
		public Keyword getResponsibleKeyword_10_3_0() { return cResponsibleKeyword_10_3_0; }

		//responsible+=[basedsl::User|QualifiedName]
		public Assignment getResponsibleAssignment_10_3_1() { return cResponsibleAssignment_10_3_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getResponsibleUserCrossReference_10_3_1_0() { return cResponsibleUserCrossReference_10_3_1_0; }

		//QualifiedName
		public RuleCall getResponsibleUserQualifiedNameParserRuleCall_10_3_1_0_1() { return cResponsibleUserQualifiedNameParserRuleCall_10_3_1_0_1; }

		//("budgeting" budgeting=[basedsl::User|QualifiedName])?
		public Group getGroup_10_4() { return cGroup_10_4; }

		//"budgeting"
		public Keyword getBudgetingKeyword_10_4_0() { return cBudgetingKeyword_10_4_0; }

		//budgeting=[basedsl::User|QualifiedName]
		public Assignment getBudgetingAssignment_10_4_1() { return cBudgetingAssignment_10_4_1; }

		//[basedsl::User|QualifiedName]
		public CrossReference getBudgetingUserCrossReference_10_4_1_0() { return cBudgetingUserCrossReference_10_4_1_0; }

		//QualifiedName
		public RuleCall getBudgetingUserQualifiedNameParserRuleCall_10_4_1_0_1() { return cBudgetingUserQualifiedNameParserRuleCall_10_4_1_0_1; }

		//("subscriptions" "{" subscriptions+=[basedsl::User|QualifiedName]* "}")?
		public Group getGroup_10_5() { return cGroup_10_5; }

		//"subscriptions"
		public Keyword getSubscriptionsKeyword_10_5_0() { return cSubscriptionsKeyword_10_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_5_1() { return cLeftCurlyBracketKeyword_10_5_1; }

		//subscriptions+=[basedsl::User|QualifiedName]*
		public Assignment getSubscriptionsAssignment_10_5_2() { return cSubscriptionsAssignment_10_5_2; }

		//[basedsl::User|QualifiedName]
		public CrossReference getSubscriptionsUserCrossReference_10_5_2_0() { return cSubscriptionsUserCrossReference_10_5_2_0; }

		//QualifiedName
		public RuleCall getSubscriptionsUserQualifiedNameParserRuleCall_10_5_2_0_1() { return cSubscriptionsUserQualifiedNameParserRuleCall_10_5_2_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10_5_3() { return cRightCurlyBracketKeyword_10_5_3; }

		//("tags" tags+=[semanticsDsl::Tag]+)?
		public Group getGroup_11() { return cGroup_11; }

		//"tags"
		public Keyword getTagsKeyword_11_0() { return cTagsKeyword_11_0; }

		//tags+=[semanticsDsl::Tag]+
		public Assignment getTagsAssignment_11_1() { return cTagsAssignment_11_1; }

		//[semanticsDsl::Tag]
		public CrossReference getTagsTagCrossReference_11_1_0() { return cTagsTagCrossReference_11_1_0; }

		//ID
		public RuleCall getTagsTagIDTerminalRuleCall_11_1_0_1() { return cTagsTagIDTerminalRuleCall_11_1_0_1; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_12() { return cFeaturesAssignment_12; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_12_0() { return cFeaturesFeatureParserRuleCall_12_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class ServiceRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ServiceRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cServiceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cServiceServiceCrossReference_0_0 = (CrossReference)cServiceAssignment_0.eContents().get(0);
		private final RuleCall cServiceServiceQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cServiceServiceCrossReference_0_0.eContents().get(1);
		private final Assignment cVersionRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionRefVersionRefParserRuleCall_1_0 = (RuleCall)cVersionRefAssignment_1.eContents().get(0);
		private final Assignment cIsResponseHandlerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cIsResponseHandlerHandlingResponsesKeyword_2_0 = (Keyword)cIsResponseHandlerAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCallingKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCalledOperationsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCalledOperationsSimpleOperationRefParserRuleCall_3_1_0 = (RuleCall)cCalledOperationsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cCalledOperationsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cCalledOperationsSimpleOperationRefParserRuleCall_3_2_1_0 = (RuleCall)cCalledOperationsAssignment_3_2_1.eContents().get(0);
		
		//ServiceRef:
		//	service=[serviceDsl::Service|QualifiedName] versionRef=VersionRef isResponseHandler?="handling responses"? ("calling"
		//	calledOperations+=SimpleOperationRef ("," calledOperations+=SimpleOperationRef)*)?;
		public ParserRule getRule() { return rule; }

		//service=[serviceDsl::Service|QualifiedName] versionRef=VersionRef isResponseHandler?="handling responses"? ("calling"
		//calledOperations+=SimpleOperationRef ("," calledOperations+=SimpleOperationRef)*)?
		public Group getGroup() { return cGroup; }

		//service=[serviceDsl::Service|QualifiedName]
		public Assignment getServiceAssignment_0() { return cServiceAssignment_0; }

		//[serviceDsl::Service|QualifiedName]
		public CrossReference getServiceServiceCrossReference_0_0() { return cServiceServiceCrossReference_0_0; }

		//QualifiedName
		public RuleCall getServiceServiceQualifiedNameParserRuleCall_0_0_1() { return cServiceServiceQualifiedNameParserRuleCall_0_0_1; }

		//versionRef=VersionRef
		public Assignment getVersionRefAssignment_1() { return cVersionRefAssignment_1; }

		//VersionRef
		public RuleCall getVersionRefVersionRefParserRuleCall_1_0() { return cVersionRefVersionRefParserRuleCall_1_0; }

		//isResponseHandler?="handling responses"?
		public Assignment getIsResponseHandlerAssignment_2() { return cIsResponseHandlerAssignment_2; }

		//"handling responses"
		public Keyword getIsResponseHandlerHandlingResponsesKeyword_2_0() { return cIsResponseHandlerHandlingResponsesKeyword_2_0; }

		//("calling" calledOperations+=SimpleOperationRef ("," calledOperations+=SimpleOperationRef)*)?
		public Group getGroup_3() { return cGroup_3; }

		//"calling"
		public Keyword getCallingKeyword_3_0() { return cCallingKeyword_3_0; }

		//calledOperations+=SimpleOperationRef
		public Assignment getCalledOperationsAssignment_3_1() { return cCalledOperationsAssignment_3_1; }

		//SimpleOperationRef
		public RuleCall getCalledOperationsSimpleOperationRefParserRuleCall_3_1_0() { return cCalledOperationsSimpleOperationRefParserRuleCall_3_1_0; }

		//("," calledOperations+=SimpleOperationRef)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//calledOperations+=SimpleOperationRef
		public Assignment getCalledOperationsAssignment_3_2_1() { return cCalledOperationsAssignment_3_2_1; }

		//SimpleOperationRef
		public RuleCall getCalledOperationsSimpleOperationRefParserRuleCall_3_2_1_0() { return cCalledOperationsSimpleOperationRefParserRuleCall_3_2_1_0; }
	}

	public class SimpleOperationRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleOperationRef");
		private final Assignment cOperationAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cOperationOperationCrossReference_0 = (CrossReference)cOperationAssignment.eContents().get(0);
		private final RuleCall cOperationOperationQualifiedNameParserRuleCall_0_1 = (RuleCall)cOperationOperationCrossReference_0.eContents().get(1);
		
		//SimpleOperationRef:
		//	operation=[serviceDsl::Operation|QualifiedName];
		public ParserRule getRule() { return rule; }

		//operation=[serviceDsl::Operation|QualifiedName]
		public Assignment getOperationAssignment() { return cOperationAssignment; }

		//[serviceDsl::Operation|QualifiedName]
		public CrossReference getOperationOperationCrossReference_0() { return cOperationOperationCrossReference_0; }

		//QualifiedName
		public RuleCall getOperationOperationQualifiedNameParserRuleCall_0_1() { return cOperationOperationQualifiedNameParserRuleCall_0_1; }
	}

	public class CapabilityRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CapabilityRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCapabilityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cCapabilityCapabilityCrossReference_0_0 = (CrossReference)cCapabilityAssignment_0.eContents().get(0);
		private final RuleCall cCapabilityCapabilityQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cCapabilityCapabilityCrossReference_0_0.eContents().get(1);
		private final Assignment cVersionRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionRefVersionRefParserRuleCall_1_0 = (RuleCall)cVersionRefAssignment_1.eContents().get(0);
		
		//CapabilityRef:
		//	capability=[businessDsl::Capability|QualifiedName] versionRef=VersionRef;
		public ParserRule getRule() { return rule; }

		//capability=[businessDsl::Capability|QualifiedName] versionRef=VersionRef
		public Group getGroup() { return cGroup; }

		//capability=[businessDsl::Capability|QualifiedName]
		public Assignment getCapabilityAssignment_0() { return cCapabilityAssignment_0; }

		//[businessDsl::Capability|QualifiedName]
		public CrossReference getCapabilityCapabilityCrossReference_0_0() { return cCapabilityCapabilityCrossReference_0_0; }

		//QualifiedName
		public RuleCall getCapabilityCapabilityQualifiedNameParserRuleCall_0_0_1() { return cCapabilityCapabilityQualifiedNameParserRuleCall_0_0_1; }

		//versionRef=VersionRef
		public Assignment getVersionRefAssignment_1() { return cVersionRefAssignment_1; }

		//VersionRef
		public RuleCall getVersionRefVersionRefParserRuleCall_1_0() { return cVersionRefVersionRefParserRuleCall_1_0; }
	}

	public class VersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Version");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVersionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVersionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionVersionIdParserRuleCall_1_0 = (RuleCall)cVersionAssignment_1.eContents().get(0);
		
		//Version:
		//	"version" version=VersionId;
		public ParserRule getRule() { return rule; }

		//"version" version=VersionId
		public Group getGroup() { return cGroup; }

		//"version"
		public Keyword getVersionKeyword_0() { return cVersionKeyword_0; }

		//version=VersionId
		public Assignment getVersionAssignment_1() { return cVersionAssignment_1; }

		//VersionId
		public RuleCall getVersionVersionIdParserRuleCall_1_0() { return cVersionVersionIdParserRuleCall_1_0; }
	}

	public class ProductVersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ProductVersion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProductVersionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVersionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionVersionIdParserRuleCall_1_0 = (RuleCall)cVersionAssignment_1.eContents().get(0);
		
		//ProductVersion returns Version:
		//	"product-version" version=VersionId;
		public ParserRule getRule() { return rule; }

		//"product-version" version=VersionId
		public Group getGroup() { return cGroup; }

		//"product-version"
		public Keyword getProductVersionKeyword_0() { return cProductVersionKeyword_0; }

		//version=VersionId
		public Assignment getVersionAssignment_1() { return cVersionAssignment_1; }

		//VersionId
		public RuleCall getVersionVersionIdParserRuleCall_1_0() { return cVersionVersionIdParserRuleCall_1_0; }
	}

	public class EventRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EventRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEventAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEventEventCrossReference_0_0 = (CrossReference)cEventAssignment_0.eContents().get(0);
		private final RuleCall cEventEventQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cEventEventCrossReference_0_0.eContents().get(1);
		private final Assignment cVersionRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionRefVersionRefParserRuleCall_1_0 = (RuleCall)cVersionRefAssignment_1.eContents().get(0);
		
		//EventRef:
		//	event=[serviceDsl::Event|QualifiedName] versionRef=VersionRef;
		public ParserRule getRule() { return rule; }

		//event=[serviceDsl::Event|QualifiedName] versionRef=VersionRef
		public Group getGroup() { return cGroup; }

		//event=[serviceDsl::Event|QualifiedName]
		public Assignment getEventAssignment_0() { return cEventAssignment_0; }

		//[serviceDsl::Event|QualifiedName]
		public CrossReference getEventEventCrossReference_0_0() { return cEventEventCrossReference_0_0; }

		//QualifiedName
		public RuleCall getEventEventQualifiedNameParserRuleCall_0_0_1() { return cEventEventQualifiedNameParserRuleCall_0_0_1; }

		//versionRef=VersionRef
		public Assignment getVersionRefAssignment_1() { return cVersionRefAssignment_1; }

		//VersionRef
		public RuleCall getVersionRefVersionRefParserRuleCall_1_0() { return cVersionRefVersionRefParserRuleCall_1_0; }
	}
	
	
	public class ModuleKindElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ModuleKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUIEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUIUIKeyword_0_0 = (Keyword)cUIEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBusinessLogicEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBusinessLogicBusinessLogicKeyword_1_0 = (Keyword)cBusinessLogicEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPersistenceEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPersistencePersistenceKeyword_2_0 = (Keyword)cPersistenceEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSecurityEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSecuritySecurityKeyword_3_0 = (Keyword)cSecurityEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cBatchEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cBatchBatchKeyword_4_0 = (Keyword)cBatchEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cOTHEREnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cOTHEROTHERKeyword_5_0 = (Keyword)cOTHEREnumLiteralDeclaration_5.eContents().get(0);
		
		//enum ModuleKind:
		//	UI | BusinessLogic | Persistence | Security | Batch | OTHER;
		public EnumRule getRule() { return rule; }

		//UI | BusinessLogic | Persistence | Security | Batch | OTHER
		public Alternatives getAlternatives() { return cAlternatives; }

		//UI
		public EnumLiteralDeclaration getUIEnumLiteralDeclaration_0() { return cUIEnumLiteralDeclaration_0; }

		//"UI"
		public Keyword getUIUIKeyword_0_0() { return cUIUIKeyword_0_0; }

		//BusinessLogic
		public EnumLiteralDeclaration getBusinessLogicEnumLiteralDeclaration_1() { return cBusinessLogicEnumLiteralDeclaration_1; }

		//"BusinessLogic"
		public Keyword getBusinessLogicBusinessLogicKeyword_1_0() { return cBusinessLogicBusinessLogicKeyword_1_0; }

		//Persistence
		public EnumLiteralDeclaration getPersistenceEnumLiteralDeclaration_2() { return cPersistenceEnumLiteralDeclaration_2; }

		//"Persistence"
		public Keyword getPersistencePersistenceKeyword_2_0() { return cPersistencePersistenceKeyword_2_0; }

		//Security
		public EnumLiteralDeclaration getSecurityEnumLiteralDeclaration_3() { return cSecurityEnumLiteralDeclaration_3; }

		//"Security"
		public Keyword getSecuritySecurityKeyword_3_0() { return cSecuritySecurityKeyword_3_0; }

		//Batch
		public EnumLiteralDeclaration getBatchEnumLiteralDeclaration_4() { return cBatchEnumLiteralDeclaration_4; }

		//"Batch"
		public Keyword getBatchBatchKeyword_4_0() { return cBatchBatchKeyword_4_0; }

		//OTHER
		public EnumLiteralDeclaration getOTHEREnumLiteralDeclaration_5() { return cOTHEREnumLiteralDeclaration_5; }

		//"OTHER"
		public Keyword getOTHEROTHERKeyword_5_0() { return cOTHEROTHERKeyword_5_0; }
	}
	
	private ModelElements pModel;
	private SolutionElements pSolution;
	private ModuleElements pModule;
	private ModuleKindElements unknownRuleModuleKind;
	private FeatureElements pFeature;
	private ServiceRefElements pServiceRef;
	private SimpleOperationRefElements pSimpleOperationRef;
	private CapabilityRefElements pCapabilityRef;
	private VersionElements pVersion;
	private ProductVersionElements pProductVersion;
	private EventRefElements pEventRef;
	
	private final Grammar grammar;

	private SOABaseDslGrammarAccess gaSOABaseDsl;

	@Inject
	public SolutionDslGrammarAccess(GrammarProvider grammarProvider,
		SOABaseDslGrammarAccess gaSOABaseDsl) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaSOABaseDsl = gaSOABaseDsl;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.fornax.soa.SolutionDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public SOABaseDslGrammarAccess getSOABaseDslGrammarAccess() {
		return gaSOABaseDsl;
	}

	
	//Model:
	//	imports+=Import* solution+=Solution*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Solution:
	//	"solution" name=QualifiedName "{" ("domain" domain=[businessDsl::Domain|QualifiedName])? version=Version
	//	"lifecycle-state" state=[profileDsl::LifecycleState|QualifiedName] productVersion=ProductVersion?
	//	additionalInfo=AdditionalInformation? ("requires" requires+=ServiceRef)* features+=Feature* modules+=Module*
	//	("contacts" "{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible"
	//	responsible+=[basedsl::User|QualifiedName])* ("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions"
	//	"{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)? ("tags" tags+=[semanticsDsl::Tag]+)? "}";
	public SolutionElements getSolutionAccess() {
		return (pSolution != null) ? pSolution : (pSolution = new SolutionElements());
	}
	
	public ParserRule getSolutionRule() {
		return getSolutionAccess().getRule();
	}

	//Module:
	//	"module" name=ID "{" "kind" kind=ModuleKind version=Version? additionalInfo=AdditionalInformation? ("requires"
	//	requires+=ServiceRef)* features+=Feature* modules+=Module* ("contacts" "{" ("owner"
	//	owner=[basedsl::User|QualifiedName])? ("responsible" responsible+=[basedsl::User|QualifiedName])* ("budgeting"
	//	budgeting=[basedsl::User|QualifiedName])? ("subscriptions" "{" subscriptions+=[basedsl::User|QualifiedName]* "}")?)?
	//	("tags" tags+=[semanticsDsl::Tag]+)? "}";
	public ModuleElements getModuleAccess() {
		return (pModule != null) ? pModule : (pModule = new ModuleElements());
	}
	
	public ParserRule getModuleRule() {
		return getModuleAccess().getRule();
	}

	//enum ModuleKind:
	//	UI | BusinessLogic | Persistence | Security | Batch | OTHER;
	public ModuleKindElements getModuleKindAccess() {
		return (unknownRuleModuleKind != null) ? unknownRuleModuleKind : (unknownRuleModuleKind = new ModuleKindElements());
	}
	
	public EnumRule getModuleKindRule() {
		return getModuleKindAccess().getRule();
	}

	//Feature:
	//	nonFunctional?="non-functional"? "feature" name=ID "{" ("use-cases" useCase+=STRING+)? ("description"
	//	description=STRING)? additionalInfo=AdditionalInformation? ("uses-capabilities" "{" usesCapabilities+=CapabilityRef+
	//	"}")? ("requires" requires+=ServiceRef)* ("subscribes-to-event" event+=EventRef ("," event+=EventRef)*)? ("contacts"
	//	"{" ("owner" owner=[basedsl::User|QualifiedName])? ("responsible" responsible+=[basedsl::User|QualifiedName])*
	//	("budgeting" budgeting=[basedsl::User|QualifiedName])? ("subscriptions" "{"
	//	subscriptions+=[basedsl::User|QualifiedName]* "}")?)? ("tags" tags+=[semanticsDsl::Tag]+)? features+=Feature* "}";
	public FeatureElements getFeatureAccess() {
		return (pFeature != null) ? pFeature : (pFeature = new FeatureElements());
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}

	//ServiceRef:
	//	service=[serviceDsl::Service|QualifiedName] versionRef=VersionRef isResponseHandler?="handling responses"? ("calling"
	//	calledOperations+=SimpleOperationRef ("," calledOperations+=SimpleOperationRef)*)?;
	public ServiceRefElements getServiceRefAccess() {
		return (pServiceRef != null) ? pServiceRef : (pServiceRef = new ServiceRefElements());
	}
	
	public ParserRule getServiceRefRule() {
		return getServiceRefAccess().getRule();
	}

	//SimpleOperationRef:
	//	operation=[serviceDsl::Operation|QualifiedName];
	public SimpleOperationRefElements getSimpleOperationRefAccess() {
		return (pSimpleOperationRef != null) ? pSimpleOperationRef : (pSimpleOperationRef = new SimpleOperationRefElements());
	}
	
	public ParserRule getSimpleOperationRefRule() {
		return getSimpleOperationRefAccess().getRule();
	}

	//CapabilityRef:
	//	capability=[businessDsl::Capability|QualifiedName] versionRef=VersionRef;
	public CapabilityRefElements getCapabilityRefAccess() {
		return (pCapabilityRef != null) ? pCapabilityRef : (pCapabilityRef = new CapabilityRefElements());
	}
	
	public ParserRule getCapabilityRefRule() {
		return getCapabilityRefAccess().getRule();
	}

	//Version:
	//	"version" version=VersionId;
	public VersionElements getVersionAccess() {
		return (pVersion != null) ? pVersion : (pVersion = new VersionElements());
	}
	
	public ParserRule getVersionRule() {
		return getVersionAccess().getRule();
	}

	//ProductVersion returns Version:
	//	"product-version" version=VersionId;
	public ProductVersionElements getProductVersionAccess() {
		return (pProductVersion != null) ? pProductVersion : (pProductVersion = new ProductVersionElements());
	}
	
	public ParserRule getProductVersionRule() {
		return getProductVersionAccess().getRule();
	}

	//EventRef:
	//	event=[serviceDsl::Event|QualifiedName] versionRef=VersionRef;
	public EventRefElements getEventRefAccess() {
		return (pEventRef != null) ? pEventRef : (pEventRef = new EventRefElements());
	}
	
	public ParserRule getEventRefRule() {
		return getEventRefAccess().getRule();
	}

	/// * Java like imports * / Import:
	//	"import" importedNamespace=QualifiedNameWithWildCard;
	public SOABaseDslGrammarAccess.ImportElements getImportAccess() {
		return gaSOABaseDsl.getImportAccess();
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	/// * 
	// * Version numbers, some postfixes are treated in a special way:
	// * <ul>
	// * 	<li>Final:		treated as if the version number ends with ".0"</li>
	// * 	<li>RC:			release candidate, may end with a number</li>
	// * 	<li>CR:			release candidate (snynonym for RC), may end with a number</li></li>
	// * 	<li>Beta:		beta, may end with a number</li>
	// * 	<li>Alpha:		alpha, may end with a number</li>
	// * 	<li>Milestone:	milestone release, may end with a number</li>
	// * </ul>
	// * / VersionId:
	//	INT ("." INT)* (("." | "-") ID)*;
	public SOABaseDslGrammarAccess.VersionIdElements getVersionIdAccess() {
		return gaSOABaseDsl.getVersionIdAccess();
	}
	
	public ParserRule getVersionIdRule() {
		return getVersionIdAccess().getRule();
	}

	//VersionedName:
	//	{VersionedName} QualifiedName | ID WS* version=VersionId;
	public SOABaseDslGrammarAccess.VersionedNameElements getVersionedNameAccess() {
		return gaSOABaseDsl.getVersionedNameAccess();
	}
	
	public ParserRule getVersionedNameRule() {
		return getVersionedNameAccess().getRule();
	}

	/// *
	// * Version constraints applied to referenced assets
	// * / VersionRef:
	//	MinVersionRef | MaxVersionRef | LowerBoundRangeVersionRef | MajorVersionRef | FixedVersionRef;
	public SOABaseDslGrammarAccess.VersionRefElements getVersionRefAccess() {
		return gaSOABaseDsl.getVersionRefAccess();
	}
	
	public ParserRule getVersionRefRule() {
		return getVersionRefAccess().getRule();
	}

	/// *
	// * Assets, where the version is lesser than maximal version: asset version >= minVersion
	// * / MinVersionRef:
	//	"minVersion" minVersion=VersionId;
	public SOABaseDslGrammarAccess.MinVersionRefElements getMinVersionRefAccess() {
		return gaSOABaseDsl.getMinVersionRefAccess();
	}
	
	public ParserRule getMinVersionRefRule() {
		return getMinVersionRefAccess().getRule();
	}

	/// *
	// * Assets, that match a minimal version: asset version >= minVersion
	// * / MaxVersionRef:
	//	"maxVersion" maxVersion=VersionId;
	public SOABaseDslGrammarAccess.MaxVersionRefElements getMaxVersionRefAccess() {
		return gaSOABaseDsl.getMaxVersionRefAccess();
	}
	
	public ParserRule getMaxVersionRefRule() {
		return getMaxVersionRefAccess().getRule();
	}

	/// *
	// * Matches version in the half open range [minVersion, maxVersion)
	// * / LowerBoundRangeVersionRef:
	//	("minVersion" ">=") minVersion=VersionId "," ("maxVersion" "<") maxVersion=VersionId;
	public SOABaseDslGrammarAccess.LowerBoundRangeVersionRefElements getLowerBoundRangeVersionRefAccess() {
		return gaSOABaseDsl.getLowerBoundRangeVersionRefAccess();
	}
	
	public ParserRule getLowerBoundRangeVersionRefRule() {
		return getLowerBoundRangeVersionRefAccess().getRule();
	}

	/// *
	// * Constraint matches assets with any version with the same major version, i.e. the first INT until the first '.' is equal
	// * / MajorVersionRef:
	//	"majorVersion" majorVersion=INT;
	public SOABaseDslGrammarAccess.MajorVersionRefElements getMajorVersionRefAccess() {
		return gaSOABaseDsl.getMajorVersionRefAccess();
	}
	
	public ParserRule getMajorVersionRefRule() {
		return getMajorVersionRefAccess().getRule();
	}

	/// *
	// * Constraint that matches an asset version  explicitely
	// * / FixedVersionRef:
	//	"fixedVersion" fixedVersion=VersionId;
	public SOABaseDslGrammarAccess.FixedVersionRefElements getFixedVersionRefAccess() {
		return gaSOABaseDsl.getFixedVersionRefAccess();
	}
	
	public ParserRule getFixedVersionRefRule() {
		return getFixedVersionRefAccess().getRule();
	}

	//QualifiedNameWithWildCard:
	//	QualifiedName ".*"?;
	public SOABaseDslGrammarAccess.QualifiedNameWithWildCardElements getQualifiedNameWithWildCardAccess() {
		return gaSOABaseDsl.getQualifiedNameWithWildCardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildCardRule() {
		return getQualifiedNameWithWildCardAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public SOABaseDslGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaSOABaseDsl.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	/// *
	// * Expresses SOA governance decisions
	// * voteing until date will be part of the review ballots captured in the side store
	// * / GovernanceDecision:
	//	"governance-decision" "{" ("subject" subject=STRING) ("decision-result" decisionResult=GovernanceDecisionResult)
	//	("specific-result" specificResult=STRING)? ("justification-doc" justificationOrDocURL=STRING)? ("decision-date"
	//	approvalDate=STRING)? ("decision-by" approvedBy=STRING)? ("effective-date" effectiveDate=STRING)? "}";
	public SOABaseDslGrammarAccess.GovernanceDecisionElements getGovernanceDecisionAccess() {
		return gaSOABaseDsl.getGovernanceDecisionAccess();
	}
	
	public ParserRule getGovernanceDecisionRule() {
		return getGovernanceDecisionAccess().getRule();
	}

	//enum GovernanceDecisionResult:
	//	pending | accepted | denied | specific;
	public SOABaseDslGrammarAccess.GovernanceDecisionResultElements getGovernanceDecisionResultAccess() {
		return gaSOABaseDsl.getGovernanceDecisionResultAccess();
	}
	
	public EnumRule getGovernanceDecisionResultRule() {
		return getGovernanceDecisionResultAccess().getRule();
	}

	//AbstractType:
	//	{AbstractType} name=ID;
	public SOABaseDslGrammarAccess.AbstractTypeElements getAbstractTypeAccess() {
		return gaSOABaseDsl.getAbstractTypeAccess();
	}
	
	public ParserRule getAbstractTypeRule() {
		return getAbstractTypeAccess().getRule();
	}

	//AdditionalInformation:
	//	"additional-information" "{" infoItems+=InfoItem+ "}";
	public SOABaseDslGrammarAccess.AdditionalInformationElements getAdditionalInformationAccess() {
		return gaSOABaseDsl.getAdditionalInformationAccess();
	}
	
	public ParserRule getAdditionalInformationRule() {
		return getAdditionalInformationAccess().getRule();
	}

	//InfoItem:
	//	"location" documentLocation=STRING ("reference" reference=STRING)?;
	public SOABaseDslGrammarAccess.InfoItemElements getInfoItemAccess() {
		return gaSOABaseDsl.getInfoItemAccess();
	}
	
	public ParserRule getInfoItemRule() {
		return getInfoItemAccess().getRule();
	}

	//User:
	//	name=QualifiedName firstname=STRING? lastname=STRING? org=STRING? orgUnit=STRING? email=STRING? phone=STRING?
	//	roles+=RoleRef*;
	public SOABaseDslGrammarAccess.UserElements getUserAccess() {
		return gaSOABaseDsl.getUserAccess();
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}

	//RoleRef:
	//	role=[Role|QualifiedName];
	public SOABaseDslGrammarAccess.RoleRefElements getRoleRefAccess() {
		return gaSOABaseDsl.getRoleRefAccess();
	}
	
	public ParserRule getRoleRefRule() {
		return getRoleRefAccess().getRule();
	}

	//Role:
	//	name=STRING grants+=PrivilegeRef*;
	public SOABaseDslGrammarAccess.RoleElements getRoleAccess() {
		return gaSOABaseDsl.getRoleAccess();
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}

	//PrivilegeRef:
	//	privilege=[Privilege|QualifiedName];
	public SOABaseDslGrammarAccess.PrivilegeRefElements getPrivilegeRefAccess() {
		return gaSOABaseDsl.getPrivilegeRefAccess();
	}
	
	public ParserRule getPrivilegeRefRule() {
		return getPrivilegeRefAccess().getRule();
	}

	//Privilege:
	//	name=QualifiedName readACL+=QualifiedName* writeACL+=QualifiedName* executeACL+=QualifiedName* "}";
	public SOABaseDslGrammarAccess.PrivilegeElements getPrivilegeAccess() {
		return gaSOABaseDsl.getPrivilegeAccess();
	}
	
	public ParserRule getPrivilegeRule() {
		return getPrivilegeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaSOABaseDsl.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaSOABaseDsl.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaSOABaseDsl.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaSOABaseDsl.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaSOABaseDsl.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaSOABaseDsl.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaSOABaseDsl.getANY_OTHERRule();
	} 
}
