/*
* generated by Xtext
*/

package org.fornax.soa.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.fornax.soa.basedsl.services.SOABaseDslGrammarAccess;

@Singleton
public class SolutionDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Assignment cSolutionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSolutionSolutionParserRuleCall_1_0 = (RuleCall)cSolutionAssignment_1.eContents().get(0);
		
		//Model hidden(WS):
		//	imports+=Import* solution+=Solution*;
		public ParserRule getRule() { return rule; }

		//imports+=Import* solution+=Solution*
		public Group getGroup() { return cGroup; }

		//imports+=Import*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }

		//Import
		public RuleCall getImportsImportParserRuleCall_0_0() { return cImportsImportParserRuleCall_0_0; }

		//solution+=Solution*
		public Assignment getSolutionAssignment_1() { return cSolutionAssignment_1; }

		//Solution
		public RuleCall getSolutionSolutionParserRuleCall_1_0() { return cSolutionSolutionParserRuleCall_1_0; }
	}

	public class SolutionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Solution");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSolutionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDomainKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDomainAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cDomainDomainCrossReference_3_1_0 = (CrossReference)cDomainAssignment_3_1.eContents().get(0);
		private final RuleCall cDomainDomainQualifiedNameParserRuleCall_3_1_0_1 = (RuleCall)cDomainDomainCrossReference_3_1_0.eContents().get(1);
		private final Assignment cVersionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVersionVersionParserRuleCall_4_0 = (RuleCall)cVersionAssignment_4.eContents().get(0);
		private final Assignment cProductVersionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cProductVersionProductVersionParserRuleCall_5_0 = (RuleCall)cProductVersionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRequiresKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRequiresAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cRequiresServiceRefParserRuleCall_6_1_0 = (RuleCall)cRequiresAssignment_6_1.eContents().get(0);
		private final Assignment cFeaturesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFeaturesFeatureParserRuleCall_7_0 = (RuleCall)cFeaturesAssignment_7.eContents().get(0);
		private final Assignment cModulesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cModulesModuleParserRuleCall_8_0 = (RuleCall)cModulesAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cTagsKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cTagsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cTagsTagCrossReference_9_1_0 = (CrossReference)cTagsAssignment_9_1.eContents().get(0);
		private final RuleCall cTagsTagIDTerminalRuleCall_9_1_0_1 = (RuleCall)cTagsTagCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Solution hidden(WS):
		//	"solution" name=QualifiedName "{" ("domain" domain=[businessDsl::Domain|QualifiedName])? version=Version
		//	productVersion=ProductVersion? ("requires" requires+=ServiceRef)* features+=Feature* modules+=Module* ("tags"
		//	tags+=[semanticsDsl::Tag]+)? "}";
		public ParserRule getRule() { return rule; }

		//"solution" name=QualifiedName "{" ("domain" domain=[businessDsl::Domain|QualifiedName])? version=Version
		//productVersion=ProductVersion? ("requires" requires+=ServiceRef)* features+=Feature* modules+=Module* ("tags"
		//tags+=[semanticsDsl::Tag]+)? "}"
		public Group getGroup() { return cGroup; }

		//"solution"
		public Keyword getSolutionKeyword_0() { return cSolutionKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("domain" domain=[businessDsl::Domain|QualifiedName])?
		public Group getGroup_3() { return cGroup_3; }

		//"domain"
		public Keyword getDomainKeyword_3_0() { return cDomainKeyword_3_0; }

		//domain=[businessDsl::Domain|QualifiedName]
		public Assignment getDomainAssignment_3_1() { return cDomainAssignment_3_1; }

		//[businessDsl::Domain|QualifiedName]
		public CrossReference getDomainDomainCrossReference_3_1_0() { return cDomainDomainCrossReference_3_1_0; }

		//QualifiedName
		public RuleCall getDomainDomainQualifiedNameParserRuleCall_3_1_0_1() { return cDomainDomainQualifiedNameParserRuleCall_3_1_0_1; }

		//version=Version
		public Assignment getVersionAssignment_4() { return cVersionAssignment_4; }

		//Version
		public RuleCall getVersionVersionParserRuleCall_4_0() { return cVersionVersionParserRuleCall_4_0; }

		//productVersion=ProductVersion?
		public Assignment getProductVersionAssignment_5() { return cProductVersionAssignment_5; }

		//ProductVersion
		public RuleCall getProductVersionProductVersionParserRuleCall_5_0() { return cProductVersionProductVersionParserRuleCall_5_0; }

		//("requires" requires+=ServiceRef)*
		public Group getGroup_6() { return cGroup_6; }

		//"requires"
		public Keyword getRequiresKeyword_6_0() { return cRequiresKeyword_6_0; }

		//requires+=ServiceRef
		public Assignment getRequiresAssignment_6_1() { return cRequiresAssignment_6_1; }

		//ServiceRef
		public RuleCall getRequiresServiceRefParserRuleCall_6_1_0() { return cRequiresServiceRefParserRuleCall_6_1_0; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_7() { return cFeaturesAssignment_7; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_7_0() { return cFeaturesFeatureParserRuleCall_7_0; }

		//modules+=Module*
		public Assignment getModulesAssignment_8() { return cModulesAssignment_8; }

		//Module
		public RuleCall getModulesModuleParserRuleCall_8_0() { return cModulesModuleParserRuleCall_8_0; }

		//("tags" tags+=[semanticsDsl::Tag]+)?
		public Group getGroup_9() { return cGroup_9; }

		//"tags"
		public Keyword getTagsKeyword_9_0() { return cTagsKeyword_9_0; }

		//tags+=[semanticsDsl::Tag]+
		public Assignment getTagsAssignment_9_1() { return cTagsAssignment_9_1; }

		//[semanticsDsl::Tag]
		public CrossReference getTagsTagCrossReference_9_1_0() { return cTagsTagCrossReference_9_1_0; }

		//ID
		public RuleCall getTagsTagIDTerminalRuleCall_9_1_0_1() { return cTagsTagIDTerminalRuleCall_9_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class ModuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Module");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cKindKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cKindAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cKindModuleKindEnumRuleCall_4_0 = (RuleCall)cKindAssignment_4.eContents().get(0);
		private final Assignment cVersionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cVersionVersionParserRuleCall_5_0 = (RuleCall)cVersionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRequiresKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRequiresAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cRequiresServiceRefParserRuleCall_6_1_0 = (RuleCall)cRequiresAssignment_6_1.eContents().get(0);
		private final Assignment cFeaturesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFeaturesFeatureParserRuleCall_7_0 = (RuleCall)cFeaturesAssignment_7.eContents().get(0);
		private final Assignment cModulesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cModulesModuleParserRuleCall_8_0 = (RuleCall)cModulesAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cTagsKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cTagsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cTagsTagCrossReference_9_1_0 = (CrossReference)cTagsAssignment_9_1.eContents().get(0);
		private final RuleCall cTagsTagIDTerminalRuleCall_9_1_0_1 = (RuleCall)cTagsTagCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Module hidden(WS):
		//	"module" name=ID "{" "kind" kind=ModuleKind version=Version? ("requires" requires+=ServiceRef)* features+=Feature*
		//	modules+=Module* ("tags" tags+=[semanticsDsl::Tag]+)? "}";
		public ParserRule getRule() { return rule; }

		//"module" name=ID "{" "kind" kind=ModuleKind version=Version? ("requires" requires+=ServiceRef)* features+=Feature*
		//modules+=Module* ("tags" tags+=[semanticsDsl::Tag]+)? "}"
		public Group getGroup() { return cGroup; }

		//"module"
		public Keyword getModuleKeyword_0() { return cModuleKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"kind"
		public Keyword getKindKeyword_3() { return cKindKeyword_3; }

		//kind=ModuleKind
		public Assignment getKindAssignment_4() { return cKindAssignment_4; }

		//ModuleKind
		public RuleCall getKindModuleKindEnumRuleCall_4_0() { return cKindModuleKindEnumRuleCall_4_0; }

		//version=Version?
		public Assignment getVersionAssignment_5() { return cVersionAssignment_5; }

		//Version
		public RuleCall getVersionVersionParserRuleCall_5_0() { return cVersionVersionParserRuleCall_5_0; }

		//("requires" requires+=ServiceRef)*
		public Group getGroup_6() { return cGroup_6; }

		//"requires"
		public Keyword getRequiresKeyword_6_0() { return cRequiresKeyword_6_0; }

		//requires+=ServiceRef
		public Assignment getRequiresAssignment_6_1() { return cRequiresAssignment_6_1; }

		//ServiceRef
		public RuleCall getRequiresServiceRefParserRuleCall_6_1_0() { return cRequiresServiceRefParserRuleCall_6_1_0; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_7() { return cFeaturesAssignment_7; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_7_0() { return cFeaturesFeatureParserRuleCall_7_0; }

		//modules+=Module*
		public Assignment getModulesAssignment_8() { return cModulesAssignment_8; }

		//Module
		public RuleCall getModulesModuleParserRuleCall_8_0() { return cModulesModuleParserRuleCall_8_0; }

		//("tags" tags+=[semanticsDsl::Tag]+)?
		public Group getGroup_9() { return cGroup_9; }

		//"tags"
		public Keyword getTagsKeyword_9_0() { return cTagsKeyword_9_0; }

		//tags+=[semanticsDsl::Tag]+
		public Assignment getTagsAssignment_9_1() { return cTagsAssignment_9_1; }

		//[semanticsDsl::Tag]
		public CrossReference getTagsTagCrossReference_9_1_0() { return cTagsTagCrossReference_9_1_0; }

		//ID
		public RuleCall getTagsTagIDTerminalRuleCall_9_1_0_1() { return cTagsTagIDTerminalRuleCall_9_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNonFunctionalAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNonFunctionalNonFunctionalKeyword_0_0 = (Keyword)cNonFunctionalAssignment_0.eContents().get(0);
		private final Keyword cFeatureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUseCasesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUseCaseAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUseCaseSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cUseCaseAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cUsesCapabilitiesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cUsesCapabilitiesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cUsesCapabilitiesCapabilityRefParserRuleCall_6_2_0 = (RuleCall)cUsesCapabilitiesAssignment_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRequiresKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cRequiresAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cRequiresServiceRefParserRuleCall_7_1_0 = (RuleCall)cRequiresAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cSubscibesToEventKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cEventAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cEventEventRefParserRuleCall_8_1_0 = (RuleCall)cEventAssignment_8_1.eContents().get(0);
		private final Group cGroup_8_2 = (Group)cGroup_8.eContents().get(2);
		private final Keyword cCommaKeyword_8_2_0 = (Keyword)cGroup_8_2.eContents().get(0);
		private final Assignment cEventAssignment_8_2_1 = (Assignment)cGroup_8_2.eContents().get(1);
		private final RuleCall cEventEventRefParserRuleCall_8_2_1_0 = (RuleCall)cEventAssignment_8_2_1.eContents().get(0);
		private final Assignment cFeaturesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFeaturesFeatureParserRuleCall_9_0 = (RuleCall)cFeaturesAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cTagsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cTagsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cTagsTagCrossReference_10_1_0 = (CrossReference)cTagsAssignment_10_1.eContents().get(0);
		private final RuleCall cTagsTagIDTerminalRuleCall_10_1_0_1 = (RuleCall)cTagsTagCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Feature hidden(WS):
		//	nonFunctional?="non-functional"? "feature" name=ID "{" ("use cases" useCase+=STRING+)? ("description"
		//	description=STRING)? ("uses capabilities" "{" usesCapabilities+=CapabilityRef+ "}")? ("requires"
		//	requires+=ServiceRef)* ("subscibes-to-event" event+=EventRef ("," event+=EventRef)*)? features+=Feature* ("tags"
		//	tags+=[semanticsDsl::Tag]+)? "}";
		public ParserRule getRule() { return rule; }

		//nonFunctional?="non-functional"? "feature" name=ID "{" ("use cases" useCase+=STRING+)? ("description"
		//description=STRING)? ("uses capabilities" "{" usesCapabilities+=CapabilityRef+ "}")? ("requires" requires+=ServiceRef)*
		//("subscibes-to-event" event+=EventRef ("," event+=EventRef)*)? features+=Feature* ("tags" tags+=[semanticsDsl::Tag]+)?
		//"}"
		public Group getGroup() { return cGroup; }

		//nonFunctional?="non-functional"?
		public Assignment getNonFunctionalAssignment_0() { return cNonFunctionalAssignment_0; }

		//"non-functional"
		public Keyword getNonFunctionalNonFunctionalKeyword_0_0() { return cNonFunctionalNonFunctionalKeyword_0_0; }

		//"feature"
		public Keyword getFeatureKeyword_1() { return cFeatureKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("use cases" useCase+=STRING+)?
		public Group getGroup_4() { return cGroup_4; }

		//"use cases"
		public Keyword getUseCasesKeyword_4_0() { return cUseCasesKeyword_4_0; }

		//useCase+=STRING+
		public Assignment getUseCaseAssignment_4_1() { return cUseCaseAssignment_4_1; }

		//STRING
		public RuleCall getUseCaseSTRINGTerminalRuleCall_4_1_0() { return cUseCaseSTRINGTerminalRuleCall_4_1_0; }

		//("description" description=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"description"
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_1_0() { return cDescriptionSTRINGTerminalRuleCall_5_1_0; }

		//("uses capabilities" "{" usesCapabilities+=CapabilityRef+ "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"uses capabilities"
		public Keyword getUsesCapabilitiesKeyword_6_0() { return cUsesCapabilitiesKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//usesCapabilities+=CapabilityRef+
		public Assignment getUsesCapabilitiesAssignment_6_2() { return cUsesCapabilitiesAssignment_6_2; }

		//CapabilityRef
		public RuleCall getUsesCapabilitiesCapabilityRefParserRuleCall_6_2_0() { return cUsesCapabilitiesCapabilityRefParserRuleCall_6_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_3() { return cRightCurlyBracketKeyword_6_3; }

		//("requires" requires+=ServiceRef)*
		public Group getGroup_7() { return cGroup_7; }

		//"requires"
		public Keyword getRequiresKeyword_7_0() { return cRequiresKeyword_7_0; }

		//requires+=ServiceRef
		public Assignment getRequiresAssignment_7_1() { return cRequiresAssignment_7_1; }

		//ServiceRef
		public RuleCall getRequiresServiceRefParserRuleCall_7_1_0() { return cRequiresServiceRefParserRuleCall_7_1_0; }

		//("subscibes-to-event" event+=EventRef ("," event+=EventRef)*)?
		public Group getGroup_8() { return cGroup_8; }

		//"subscibes-to-event"
		public Keyword getSubscibesToEventKeyword_8_0() { return cSubscibesToEventKeyword_8_0; }

		//event+=EventRef
		public Assignment getEventAssignment_8_1() { return cEventAssignment_8_1; }

		//EventRef
		public RuleCall getEventEventRefParserRuleCall_8_1_0() { return cEventEventRefParserRuleCall_8_1_0; }

		//("," event+=EventRef)*
		public Group getGroup_8_2() { return cGroup_8_2; }

		//","
		public Keyword getCommaKeyword_8_2_0() { return cCommaKeyword_8_2_0; }

		//event+=EventRef
		public Assignment getEventAssignment_8_2_1() { return cEventAssignment_8_2_1; }

		//EventRef
		public RuleCall getEventEventRefParserRuleCall_8_2_1_0() { return cEventEventRefParserRuleCall_8_2_1_0; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_9() { return cFeaturesAssignment_9; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_9_0() { return cFeaturesFeatureParserRuleCall_9_0; }

		//("tags" tags+=[semanticsDsl::Tag]+)?
		public Group getGroup_10() { return cGroup_10; }

		//"tags"
		public Keyword getTagsKeyword_10_0() { return cTagsKeyword_10_0; }

		//tags+=[semanticsDsl::Tag]+
		public Assignment getTagsAssignment_10_1() { return cTagsAssignment_10_1; }

		//[semanticsDsl::Tag]
		public CrossReference getTagsTagCrossReference_10_1_0() { return cTagsTagCrossReference_10_1_0; }

		//ID
		public RuleCall getTagsTagIDTerminalRuleCall_10_1_0_1() { return cTagsTagIDTerminalRuleCall_10_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class ServiceRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ServiceRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cServiceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cServiceServiceCrossReference_0_0 = (CrossReference)cServiceAssignment_0.eContents().get(0);
		private final RuleCall cServiceServiceQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cServiceServiceCrossReference_0_0.eContents().get(1);
		private final Assignment cVersionRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionRefVersionRefParserRuleCall_1_0 = (RuleCall)cVersionRefAssignment_1.eContents().get(0);
		private final Assignment cIsResponseHandlerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cIsResponseHandlerHandlingResponsesKeyword_2_0 = (Keyword)cIsResponseHandlerAssignment_2.eContents().get(0);
		
		//ServiceRef:
		//	service=[serviceDsl::Service|QualifiedName] versionRef=VersionRef isResponseHandler?="handling responses"?;
		public ParserRule getRule() { return rule; }

		//service=[serviceDsl::Service|QualifiedName] versionRef=VersionRef isResponseHandler?="handling responses"?
		public Group getGroup() { return cGroup; }

		//service=[serviceDsl::Service|QualifiedName]
		public Assignment getServiceAssignment_0() { return cServiceAssignment_0; }

		//[serviceDsl::Service|QualifiedName]
		public CrossReference getServiceServiceCrossReference_0_0() { return cServiceServiceCrossReference_0_0; }

		//QualifiedName
		public RuleCall getServiceServiceQualifiedNameParserRuleCall_0_0_1() { return cServiceServiceQualifiedNameParserRuleCall_0_0_1; }

		//versionRef=VersionRef
		public Assignment getVersionRefAssignment_1() { return cVersionRefAssignment_1; }

		//VersionRef
		public RuleCall getVersionRefVersionRefParserRuleCall_1_0() { return cVersionRefVersionRefParserRuleCall_1_0; }

		//isResponseHandler?="handling responses"?
		public Assignment getIsResponseHandlerAssignment_2() { return cIsResponseHandlerAssignment_2; }

		//"handling responses"
		public Keyword getIsResponseHandlerHandlingResponsesKeyword_2_0() { return cIsResponseHandlerHandlingResponsesKeyword_2_0; }
	}

	public class CapabilityRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CapabilityRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCapabilityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cCapabilityCapabilityCrossReference_0_0 = (CrossReference)cCapabilityAssignment_0.eContents().get(0);
		private final RuleCall cCapabilityCapabilityQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cCapabilityCapabilityCrossReference_0_0.eContents().get(1);
		private final Assignment cVersionRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionRefVersionRefParserRuleCall_1_0 = (RuleCall)cVersionRefAssignment_1.eContents().get(0);
		
		//CapabilityRef:
		//	capability=[businessDsl::Capability|QualifiedName] versionRef=VersionRef;
		public ParserRule getRule() { return rule; }

		//capability=[businessDsl::Capability|QualifiedName] versionRef=VersionRef
		public Group getGroup() { return cGroup; }

		//capability=[businessDsl::Capability|QualifiedName]
		public Assignment getCapabilityAssignment_0() { return cCapabilityAssignment_0; }

		//[businessDsl::Capability|QualifiedName]
		public CrossReference getCapabilityCapabilityCrossReference_0_0() { return cCapabilityCapabilityCrossReference_0_0; }

		//QualifiedName
		public RuleCall getCapabilityCapabilityQualifiedNameParserRuleCall_0_0_1() { return cCapabilityCapabilityQualifiedNameParserRuleCall_0_0_1; }

		//versionRef=VersionRef
		public Assignment getVersionRefAssignment_1() { return cVersionRefAssignment_1; }

		//VersionRef
		public RuleCall getVersionRefVersionRefParserRuleCall_1_0() { return cVersionRefVersionRefParserRuleCall_1_0; }
	}

	public class VersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Version");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVersionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVersionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionVersionIdParserRuleCall_1_0 = (RuleCall)cVersionAssignment_1.eContents().get(0);
		
		//Version:
		//	"version" version=VersionId;
		public ParserRule getRule() { return rule; }

		//"version" version=VersionId
		public Group getGroup() { return cGroup; }

		//"version"
		public Keyword getVersionKeyword_0() { return cVersionKeyword_0; }

		//version=VersionId
		public Assignment getVersionAssignment_1() { return cVersionAssignment_1; }

		//VersionId
		public RuleCall getVersionVersionIdParserRuleCall_1_0() { return cVersionVersionIdParserRuleCall_1_0; }
	}

	public class ProductVersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ProductVersion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProductVersionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVersionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionVersionIdParserRuleCall_1_0 = (RuleCall)cVersionAssignment_1.eContents().get(0);
		
		//ProductVersion returns Version:
		//	"product-version" version=VersionId;
		public ParserRule getRule() { return rule; }

		//"product-version" version=VersionId
		public Group getGroup() { return cGroup; }

		//"product-version"
		public Keyword getProductVersionKeyword_0() { return cProductVersionKeyword_0; }

		//version=VersionId
		public Assignment getVersionAssignment_1() { return cVersionAssignment_1; }

		//VersionId
		public RuleCall getVersionVersionIdParserRuleCall_1_0() { return cVersionVersionIdParserRuleCall_1_0; }
	}

	public class EventRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EventRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEventAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEventEventCrossReference_0_0 = (CrossReference)cEventAssignment_0.eContents().get(0);
		private final RuleCall cEventEventQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cEventEventCrossReference_0_0.eContents().get(1);
		private final Assignment cVersionRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVersionRefVersionRefParserRuleCall_1_0 = (RuleCall)cVersionRefAssignment_1.eContents().get(0);
		
		//EventRef:
		//	event=[serviceDsl::Event|QualifiedName] versionRef=VersionRef;
		public ParserRule getRule() { return rule; }

		//event=[serviceDsl::Event|QualifiedName] versionRef=VersionRef
		public Group getGroup() { return cGroup; }

		//event=[serviceDsl::Event|QualifiedName]
		public Assignment getEventAssignment_0() { return cEventAssignment_0; }

		//[serviceDsl::Event|QualifiedName]
		public CrossReference getEventEventCrossReference_0_0() { return cEventEventCrossReference_0_0; }

		//QualifiedName
		public RuleCall getEventEventQualifiedNameParserRuleCall_0_0_1() { return cEventEventQualifiedNameParserRuleCall_0_0_1; }

		//versionRef=VersionRef
		public Assignment getVersionRefAssignment_1() { return cVersionRefAssignment_1; }

		//VersionRef
		public RuleCall getVersionRefVersionRefParserRuleCall_1_0() { return cVersionRefVersionRefParserRuleCall_1_0; }
	}
	
	
	public class ModuleKindElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ModuleKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUIEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUIUIKeyword_0_0 = (Keyword)cUIEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBusinessLogicEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBusinessLogicBusinessLogicKeyword_1_0 = (Keyword)cBusinessLogicEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPersistenceEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPersistencePersistenceKeyword_2_0 = (Keyword)cPersistenceEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSecurityEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSecuritySecurityKeyword_3_0 = (Keyword)cSecurityEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cBatchEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cBatchBatchKeyword_4_0 = (Keyword)cBatchEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cOTHEREnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cOTHEROTHERKeyword_5_0 = (Keyword)cOTHEREnumLiteralDeclaration_5.eContents().get(0);
		
		//enum ModuleKind:
		//	UI | BusinessLogic | Persistence | Security | Batch | OTHER;
		public EnumRule getRule() { return rule; }

		//UI | BusinessLogic | Persistence | Security | Batch | OTHER
		public Alternatives getAlternatives() { return cAlternatives; }

		//UI
		public EnumLiteralDeclaration getUIEnumLiteralDeclaration_0() { return cUIEnumLiteralDeclaration_0; }

		//"UI"
		public Keyword getUIUIKeyword_0_0() { return cUIUIKeyword_0_0; }

		//BusinessLogic
		public EnumLiteralDeclaration getBusinessLogicEnumLiteralDeclaration_1() { return cBusinessLogicEnumLiteralDeclaration_1; }

		//"BusinessLogic"
		public Keyword getBusinessLogicBusinessLogicKeyword_1_0() { return cBusinessLogicBusinessLogicKeyword_1_0; }

		//Persistence
		public EnumLiteralDeclaration getPersistenceEnumLiteralDeclaration_2() { return cPersistenceEnumLiteralDeclaration_2; }

		//"Persistence"
		public Keyword getPersistencePersistenceKeyword_2_0() { return cPersistencePersistenceKeyword_2_0; }

		//Security
		public EnumLiteralDeclaration getSecurityEnumLiteralDeclaration_3() { return cSecurityEnumLiteralDeclaration_3; }

		//"Security"
		public Keyword getSecuritySecurityKeyword_3_0() { return cSecuritySecurityKeyword_3_0; }

		//Batch
		public EnumLiteralDeclaration getBatchEnumLiteralDeclaration_4() { return cBatchEnumLiteralDeclaration_4; }

		//"Batch"
		public Keyword getBatchBatchKeyword_4_0() { return cBatchBatchKeyword_4_0; }

		//OTHER
		public EnumLiteralDeclaration getOTHEREnumLiteralDeclaration_5() { return cOTHEREnumLiteralDeclaration_5; }

		//"OTHER"
		public Keyword getOTHEROTHERKeyword_5_0() { return cOTHEROTHERKeyword_5_0; }
	}
	
	private ModelElements pModel;
	private SolutionElements pSolution;
	private ModuleElements pModule;
	private ModuleKindElements unknownRuleModuleKind;
	private FeatureElements pFeature;
	private ServiceRefElements pServiceRef;
	private CapabilityRefElements pCapabilityRef;
	private VersionElements pVersion;
	private ProductVersionElements pProductVersion;
	private EventRefElements pEventRef;
	
	private final GrammarProvider grammarProvider;

	private SOABaseDslGrammarAccess gaSOABaseDsl;

	@Inject
	public SolutionDslGrammarAccess(GrammarProvider grammarProvider,
		SOABaseDslGrammarAccess gaSOABaseDsl) {
		this.grammarProvider = grammarProvider;
		this.gaSOABaseDsl = gaSOABaseDsl;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public SOABaseDslGrammarAccess getSOABaseDslGrammarAccess() {
		return gaSOABaseDsl;
	}

	
	//Model hidden(WS):
	//	imports+=Import* solution+=Solution*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Solution hidden(WS):
	//	"solution" name=QualifiedName "{" ("domain" domain=[businessDsl::Domain|QualifiedName])? version=Version
	//	productVersion=ProductVersion? ("requires" requires+=ServiceRef)* features+=Feature* modules+=Module* ("tags"
	//	tags+=[semanticsDsl::Tag]+)? "}";
	public SolutionElements getSolutionAccess() {
		return (pSolution != null) ? pSolution : (pSolution = new SolutionElements());
	}
	
	public ParserRule getSolutionRule() {
		return getSolutionAccess().getRule();
	}

	//Module hidden(WS):
	//	"module" name=ID "{" "kind" kind=ModuleKind version=Version? ("requires" requires+=ServiceRef)* features+=Feature*
	//	modules+=Module* ("tags" tags+=[semanticsDsl::Tag]+)? "}";
	public ModuleElements getModuleAccess() {
		return (pModule != null) ? pModule : (pModule = new ModuleElements());
	}
	
	public ParserRule getModuleRule() {
		return getModuleAccess().getRule();
	}

	//enum ModuleKind:
	//	UI | BusinessLogic | Persistence | Security | Batch | OTHER;
	public ModuleKindElements getModuleKindAccess() {
		return (unknownRuleModuleKind != null) ? unknownRuleModuleKind : (unknownRuleModuleKind = new ModuleKindElements());
	}
	
	public EnumRule getModuleKindRule() {
		return getModuleKindAccess().getRule();
	}

	//Feature hidden(WS):
	//	nonFunctional?="non-functional"? "feature" name=ID "{" ("use cases" useCase+=STRING+)? ("description"
	//	description=STRING)? ("uses capabilities" "{" usesCapabilities+=CapabilityRef+ "}")? ("requires"
	//	requires+=ServiceRef)* ("subscibes-to-event" event+=EventRef ("," event+=EventRef)*)? features+=Feature* ("tags"
	//	tags+=[semanticsDsl::Tag]+)? "}";
	public FeatureElements getFeatureAccess() {
		return (pFeature != null) ? pFeature : (pFeature = new FeatureElements());
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}

	//ServiceRef:
	//	service=[serviceDsl::Service|QualifiedName] versionRef=VersionRef isResponseHandler?="handling responses"?;
	public ServiceRefElements getServiceRefAccess() {
		return (pServiceRef != null) ? pServiceRef : (pServiceRef = new ServiceRefElements());
	}
	
	public ParserRule getServiceRefRule() {
		return getServiceRefAccess().getRule();
	}

	//CapabilityRef:
	//	capability=[businessDsl::Capability|QualifiedName] versionRef=VersionRef;
	public CapabilityRefElements getCapabilityRefAccess() {
		return (pCapabilityRef != null) ? pCapabilityRef : (pCapabilityRef = new CapabilityRefElements());
	}
	
	public ParserRule getCapabilityRefRule() {
		return getCapabilityRefAccess().getRule();
	}

	//Version:
	//	"version" version=VersionId;
	public VersionElements getVersionAccess() {
		return (pVersion != null) ? pVersion : (pVersion = new VersionElements());
	}
	
	public ParserRule getVersionRule() {
		return getVersionAccess().getRule();
	}

	//ProductVersion returns Version:
	//	"product-version" version=VersionId;
	public ProductVersionElements getProductVersionAccess() {
		return (pProductVersion != null) ? pProductVersion : (pProductVersion = new ProductVersionElements());
	}
	
	public ParserRule getProductVersionRule() {
		return getProductVersionAccess().getRule();
	}

	//EventRef:
	//	event=[serviceDsl::Event|QualifiedName] versionRef=VersionRef;
	public EventRefElements getEventRefAccess() {
		return (pEventRef != null) ? pEventRef : (pEventRef = new EventRefElements());
	}
	
	public ParserRule getEventRefRule() {
		return getEventRefAccess().getRule();
	}

	//Import:
	//	"import" importedNamespace=QualifiedNameWithWildCard;
	public SOABaseDslGrammarAccess.ImportElements getImportAccess() {
		return gaSOABaseDsl.getImportAccess();
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//VersionId:
	//	INT ("." INT)* ("." ID)?;
	public SOABaseDslGrammarAccess.VersionIdElements getVersionIdAccess() {
		return gaSOABaseDsl.getVersionIdAccess();
	}
	
	public ParserRule getVersionIdRule() {
		return getVersionIdAccess().getRule();
	}

	//VersionedName:
	//	{VersionedName} QualifiedName | ID WS* version=VersionId;
	public SOABaseDslGrammarAccess.VersionedNameElements getVersionedNameAccess() {
		return gaSOABaseDsl.getVersionedNameAccess();
	}
	
	public ParserRule getVersionedNameRule() {
		return getVersionedNameAccess().getRule();
	}

	//VersionRef:
	//	MinVersionRef | MaxVersionRef | LowerBoundRangeVersionRef | MajorVersionRef | FixedVersionRef;
	public SOABaseDslGrammarAccess.VersionRefElements getVersionRefAccess() {
		return gaSOABaseDsl.getVersionRefAccess();
	}
	
	public ParserRule getVersionRefRule() {
		return getVersionRefAccess().getRule();
	}

	//MinVersionRef:
	//	"minVersion" minVersion=VersionId;
	public SOABaseDslGrammarAccess.MinVersionRefElements getMinVersionRefAccess() {
		return gaSOABaseDsl.getMinVersionRefAccess();
	}
	
	public ParserRule getMinVersionRefRule() {
		return getMinVersionRefAccess().getRule();
	}

	//MaxVersionRef:
	//	"maxVersion" maxVersion=VersionId;
	public SOABaseDslGrammarAccess.MaxVersionRefElements getMaxVersionRefAccess() {
		return gaSOABaseDsl.getMaxVersionRefAccess();
	}
	
	public ParserRule getMaxVersionRefRule() {
		return getMaxVersionRefAccess().getRule();
	}

	//LowerBoundRangeVersionRef:
	//	("minVersion" ">=") minVersion=VersionId "," ("maxVersion" "<") maxVersion=VersionId;
	public SOABaseDslGrammarAccess.LowerBoundRangeVersionRefElements getLowerBoundRangeVersionRefAccess() {
		return gaSOABaseDsl.getLowerBoundRangeVersionRefAccess();
	}
	
	public ParserRule getLowerBoundRangeVersionRefRule() {
		return getLowerBoundRangeVersionRefAccess().getRule();
	}

	//MajorVersionRef:
	//	"majorVersion" majorVersion=INT;
	public SOABaseDslGrammarAccess.MajorVersionRefElements getMajorVersionRefAccess() {
		return gaSOABaseDsl.getMajorVersionRefAccess();
	}
	
	public ParserRule getMajorVersionRefRule() {
		return getMajorVersionRefAccess().getRule();
	}

	//FixedVersionRef:
	//	"fixedVersion" fixedVersion=VersionId;
	public SOABaseDslGrammarAccess.FixedVersionRefElements getFixedVersionRefAccess() {
		return gaSOABaseDsl.getFixedVersionRefAccess();
	}
	
	public ParserRule getFixedVersionRefRule() {
		return getFixedVersionRefAccess().getRule();
	}

	//QualifiedNameWithWildCard:
	//	QualifiedName ".*"?;
	public SOABaseDslGrammarAccess.QualifiedNameWithWildCardElements getQualifiedNameWithWildCardAccess() {
		return gaSOABaseDsl.getQualifiedNameWithWildCardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildCardRule() {
		return getQualifiedNameWithWildCardAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public SOABaseDslGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaSOABaseDsl.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Qualifier:
	//	"qualifier" qualifierName+=QualifiedName ("," qualifierName+=QualifiedName)*;
	public SOABaseDslGrammarAccess.QualifierElements getQualifierAccess() {
		return gaSOABaseDsl.getQualifierAccess();
	}
	
	public ParserRule getQualifierRule() {
		return getQualifierAccess().getRule();
	}

	//AbstractType:
	//	{AbstractType} name=ID;
	public SOABaseDslGrammarAccess.AbstractTypeElements getAbstractTypeAccess() {
		return gaSOABaseDsl.getAbstractTypeAccess();
	}
	
	public ParserRule getAbstractTypeRule() {
		return getAbstractTypeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaSOABaseDsl.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaSOABaseDsl.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaSOABaseDsl.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaSOABaseDsl.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaSOABaseDsl.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaSOABaseDsl.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaSOABaseDsl.getANY_OTHERRule();
	} 
}
