<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sOABaseDsl"
    nsURI="http://www.fornax.org/soa/basedsl/SOABaseDsl" nsPrefix="sOABaseDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LifecycleState">
    <eLiterals name="proposed" literal="proposed"/>
    <eLiterals name="defined" value="1" literal="defined"/>
    <eLiterals name="development" value="2" literal="development"/>
    <eLiterals name="test" value="3" literal="test"/>
    <eLiterals name="productive" value="4" literal="productive"/>
    <eLiterals name="deprecated" value="5" literal="deprecated"/>
    <eLiterals name="retired" value="6" literal="retired"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinVersionRef" eSuperTypes="#//VersionRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxVersionRef" eSuperTypes="#//VersionRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowerBoundRangeVersionRef" eSuperTypes="#//VersionRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MajorVersionRef" eSuperTypes="#//VersionRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="majorVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
