/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.bindingdsl.serializer;

import org.xkonnex.repo.dsl.bindingdsl.serializer.AbstractBindingDslSemanticSequencer;

public class BindingDslSemanticSequencer extends AbstractBindingDslSemanticSequencer {
}
