<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="serviceDsl"
    nsURI="http://www.fornax.org/soa/ServiceDsl" nsPrefix="serviceDsl">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orgNamespaces" upperBound="-1"
        eType="#//OrganizationNamespace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationNamespace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//SOAProfile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subNamespaces" upperBound="-1"
        eType="#//SubNamespace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubNamespace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//Version"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//SOAProfile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" unique="false" upperBound="-1"
        eType="ecore:EClass ../../../../../org.fornax.soa.semanticsdsl/src-gen/org/fornax/soa/SemanticsDsl.ecore#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
        eType="#//Exception" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//GlobalEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interalNamespaces" upperBound="-1"
        eType="#//InternalNamespace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainNamespace" eSuperTypes="#//SubNamespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" eType="ecore:EClass ../../../../../org.fornax.soa.businessdsl/src-gen/org/fornax/soa/BusinessDsl.ecore#//Domain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalNamespace" eSuperTypes="#//SubNamespace"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//Version"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//LifecycleState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governanceApproval" eType="#//GovernanceApproval"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retirementDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedDefinitionUrl"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" unique="false" upperBound="-1"
        eType="ecore:EClass ../../../../../org.fornax.soa.semanticsdsl/src-gen/org/fornax/soa/SemanticsDsl.ecore#//Tag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObject" eSuperTypes="#//VersionedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superBusinessObject" eType="#//BusinessObjectRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replaces" eType="#//BusinessObjectRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeRef" eSuperTypes="#//TypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="set" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractVersionedTypeRef" eSuperTypes="#//TypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedTypeRef" eSuperTypes="#//AbstractVersionedTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//VersionedType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="set" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumTypeRef" eSuperTypes="#//AbstractVersionedTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Enumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObjectRef" eSuperTypes="#//AbstractVersionedTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//BusinessObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shallow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBusinessKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isProvidedKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="historized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="historizingKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionIndependantKey"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//VersionedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="replaces" eType="#//EnumTypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//VISIBILITY"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//Version"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//LifecycleState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governanceApproval" eType="#//GovernanceApproval"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//ServiceCategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statefulness" eType="#//Statefulness"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistence" eType="#//Persistence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedCapabilies" upperBound="-1"
        eType="#//CapabilityRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedCapabilies" upperBound="-1"
        eType="#//CapabilityRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedContractUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="releaseDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retirementDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replaces" eType="#//ServiceRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageHeader" eType="#//MessageHeaderRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" unique="false" upperBound="-1"
        eType="ecore:EClass ../../../../../org.fornax.soa.semanticsdsl/src-gen/org/fornax/soa/SemanticsDsl.ecore#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceCategory">
    <eLiterals name="process" literal="process"/>
    <eLiterals name="rule" value="1" literal="rule"/>
    <eLiterals name="activity" value="2" literal="activity"/>
    <eLiterals name="entity" value="3" literal="entity"/>
    <eLiterals name="utility" value="4" literal="utility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GovernanceApproval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decision" eType="#//ApprovalDecision"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="justificationOrDocURL"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="approvalDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="approvedBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApprovalDecision">
    <eLiterals name="no" literal="no"/>
    <eLiterals name="yes" value="1" literal="yes"/>
    <eLiterals name="temporarily_tolerated" value="2" literal="temporarily-tolerated"/>
    <eLiterals name="tolerated" value="3" literal="tolerated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Statefulness">
    <eLiterals name="idempotent" literal="idempotent"/>
    <eLiterals name="stateless" value="1" literal="stateless"/>
    <eLiterals name="transientState" value="2" literal="transient-state"/>
    <eLiterals name="stateful" value="3" literal="stateful"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Persistence">
    <eLiterals name="none" literal="none"/>
    <eLiterals name="read" value="1" literal="read"/>
    <eLiterals name="write" value="2" literal="write"/>
    <eLiterals name="readWrite" value="3" literal="read / write"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isResponseHandler" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageHeaderRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//MessageHeader"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capability" eType="ecore:EClass ../../../../../org.fornax.soa.businessdsl/src-gen/org/fornax/soa/BusinessDsl.ecore#//Capability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedDefinitionUrl"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" unique="false" upperBound="-1"
        eType="ecore:EClass ../../../../../org.fornax.soa.semanticsdsl/src-gen/org/fornax/soa/SemanticsDsl.ecore#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//Version"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replaces" eType="#//EventRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//LifecycleState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governanceApproval" eType="#//GovernanceApproval"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retirementDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationEventRef" eSuperTypes="#//EventRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//OperationEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalEventRef" eSuperTypes="#//EventRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//GlobalEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mep" eType="#//MEP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="throws" upperBound="-1"
        eType="#//ExceptionRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callbackForOperation" upperBound="-1"
        eType="#//OperationRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishes" upperBound="-1"
        eType="#//PublishedEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribes" upperBound="-1"
        eType="#//EventRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//ServiceRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statefulness" eType="#//Statefulness"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canCompensate" upperBound="-1"
        eType="#//OperationRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageHeader" eType="#//MessageHeaderRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fetchProfile" upperBound="-1"
        eType="#//FetchProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedCapabilies" upperBound="-1"
        eType="#//CapabilityRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedCapabilies" upperBound="-1"
        eType="#//CapabilityRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublishedEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="PublishedOperationEvent" eSuperTypes="#//PublishedEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishesOpEvent" eType="#//OperationEvent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublishedGlobalEvent" eSuperTypes="#//PublishedEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishesGlobalEvent" eType="#//GlobalEventRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exception">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superException" eType="#//ExceptionRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//Version"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replaces" eType="#//ExceptionRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass ../../../../../org.fornax.soa.profiledsl/src-gen/org/fornax/soa/profiledsl/SOAProfileDsl.ecore#//LifecycleState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governanceApproval" eType="#//GovernanceApproval"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retirementDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedDefinitionUrl"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" unique="false" upperBound="-1"
        eType="ecore:EClass ../../../../../org.fornax.soa.semanticsdsl/src-gen/org/fornax/soa/SemanticsDsl.ecore#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//SimpleAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wrappedExceptions" upperBound="-1"
        eType="#//ExceptionRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exception" eType="#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MEP">
    <eLiterals name="sync" literal="sync"/>
    <eLiterals name="async" value="1" literal="async"/>
    <eLiterals name="oneway" value="2" literal="oneway"/>
    <eLiterals name="fireForget" value="3" literal="fire+forget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VISIBILITY">
    <eLiterals name="public" literal="public"/>
    <eLiterals name="domain" value="1" literal="domain"/>
    <eLiterals name="private" value="2" literal="private"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FetchProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fetchSpec" eType="#//FetchSpec"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FetchSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="EagerFetch" eSuperTypes="#//FetchSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eagerFetchAssoc" upperBound="-1"
        eType="#//ParameterRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlatFetch" eSuperTypes="#//FetchSpec"/>
</ecore:EPackage>
