/*
 * generated by Xtext
 */
package org.fornax.soa;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EnvironmentDslRuntimeModule extends org.fornax.soa.AbstractEnvironmentDslRuntimeModule {

}
