<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bindingDsl"
    nsURI="http://www.fornax.org/soa/BindingDsl" nsPrefix="bindingDsl">
  <eClassifiers xsi:type="ecore:EClass" name="BindingModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Binding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointQualifierRef" eType="#//EndpointQualifierRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governanceDecisions" upperBound="-1"
        eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//GovernanceDecision"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" upperBound="-1"
        eType="#//BindingProtocol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//Policy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertions" upperBound="-1"
        eType="#//Assertion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorQualifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" unique="false"
        upperBound="-1" eType="ecore:EClass ../../../../../org.fornax.soa.environmentdsl/src-gen/org/fornax/soa/EnvironmentDsl.ecore#//Connector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleBinding" eSuperTypes="#//Binding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ModuleRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" eType="ecore:EClass ../../../../../org.fornax.soa.environmentdsl/src-gen/org/fornax/soa/EnvironmentDsl.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provServer" eType="ecore:EClass ../../../../../org.fornax.soa.environmentdsl/src-gen/org/fornax/soa/EnvironmentDsl.ecore#//Server"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceBindings" upperBound="-1"
        eType="#//ServiceBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass ../../../../../org.fornax.soa.moduledsl/src-gen/org/fornax/soa/moduledsl/ModuleDsl.ecore#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceBinding" eSuperTypes="#//Binding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//ServiceRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedContract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedModule" eType="#//ModuleRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="#//OperationBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="ecore:EClass ../../../../../org.fornax.soa.servicedsl/src-gen/org/fornax/soa/ServiceDsl.ecore#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRef" eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//VersionRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointQualifierRef" eType="#//EndpointQualifierRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointConnector" eType="#//ConnectorQualifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass ../../../../../org.fornax.soa.servicedsl/src-gen/org/fornax/soa/ServiceDsl.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointQualifierRef" eType="#//EndpointQualifierRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governanceDecisions" upperBound="-1"
        eType="ecore:EClass http://www.fornax.org/soa/basedsl/SOABaseDsl#//GovernanceDecision"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" upperBound="-1"
        eType="#//BindingProtocol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providerProtocol" upperBound="-1"
        eType="#//BindingProtocol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//Policy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providerPolicies" upperBound="-1"
        eType="#//Policy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertions" upperBound="-1"
        eType="#//Assertion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SOAP" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="#//SOAPStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedWsdlUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SOAPStyle">
    <eLiterals name="doclitwrap" literal="document/literal-wrapped"/>
    <eLiterals name="rpclit" value="1" literal="rpc/literal"/>
    <eLiterals name="rpcenc" value="2" literal="rpc/encoded"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAP" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport" eType="#//SAPTransport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" eType="ecore:EClass ../../../../../org.fornax.soa.environmentdsl/src-gen/org/fornax/soa/EnvironmentDsl.ecore#//SapClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SAPTransport">
    <eLiterals name="IDOC" literal="IDOC"/>
    <eLiterals name="RFC" value="1" literal="RFC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EJB" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jndiName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTTP" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="#//Verb"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="REST" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="#//Verb"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//RESTFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumesFormat" eType="#//RESTFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provideFormat" eType="#//RESTFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RESTFormat">
    <eLiterals name="JSON" literal="JSON"/>
    <eLiterals name="XML" value="1" literal="XML"/>
    <eLiterals name="BISON" value="2" literal="BISON"/>
    <eLiterals name="OTHER" value="3" literal="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Verb">
    <eLiterals name="CREATE" literal="CREATE"/>
    <eLiterals name="RETRIEVE" value="1" literal="RETRIEVE"/>
    <eLiterals name="UPDATE" value="2" literal="UPDATE"/>
    <eLiterals name="DELETE" value="3" literal="DELETE"/>
    <eLiterals name="GET" value="4" literal="GET"/>
    <eLiterals name="PUT" value="5" literal="PUT"/>
    <eLiterals name="POST" value="6" literal="POST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JMS" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//TopicOrQueue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jndiName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerJndi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicOrQueue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointQualifierRefs"
        eType="#//EndpointQualifierRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic" eSuperTypes="#//TopicOrQueue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Queue" eSuperTypes="#//TopicOrQueue"/>
  <eClassifiers xsi:type="ecore:EClass" name="SCA" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="promote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultipleRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FILE" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessType" eType="#//ReadWrite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pollIntervall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTP" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessType" eType="#//ReadWrite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pollIntervall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IIOP" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lookupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AMQP" eSuperTypes="#//BindingProtocol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//TopicOrQueue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lookupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerLookupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReadWrite">
    <eLiterals name="read" literal="read"/>
    <eLiterals name="write" value="1" literal="write"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogPolicy" eSuperTypes="#//Policy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logPolicy" eType="#//LogPolicyKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityPolicy" eSuperTypes="#//Policy"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationPolicy" eSuperTypes="#//SecurityPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authTokens" upperBound="-1"
        eType="#//AuthToken" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hashAlgorithms" upperBound="-1"
        eType="#//HashAlgorithm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useNonce" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issuer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthToken">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//AuthTokenKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HashAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useBase64" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//HashAlgKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HashAlgKind">
    <eLiterals name="MD5" literal="MD5"/>
    <eLiterals name="SHA1" value="1" literal="SHA1"/>
    <eLiterals name="SHA256" value="2" literal="SHA256"/>
    <eLiterals name="RSA" value="3" literal="RSA"/>
    <eLiterals name="PlainText" value="4" literal="PlainText"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SigningPolicy" eSuperTypes="#//SecurityPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedSigningAlgorithms"
        unique="false" upperBound="-1" eType="#//SigningAlgothm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredSigningAlgorithm"
        eType="#//SigningAlgothm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signedParts" upperBound="-1"
        eType="#//MessagePartRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessagePartRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagePartRef" eType="#//MessagePartRefKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partRefExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessagePartRefKind">
    <eLiterals name="header" literal="header"/>
    <eLiterals name="body" value="1" literal="body"/>
    <eLiterals name="attachments" value="2" literal="attachments"/>
    <eLiterals name="all" value="3" literal="all"/>
    <eLiterals name="expression" value="4" literal="expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SigningAlgothm">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="SHA1" value="1" literal="SHA1"/>
    <eLiterals name="SHA256" value="2" literal="SHA256"/>
    <eLiterals name="MD5" value="3" literal="MD5"/>
    <eLiterals name="RSA_1_5" value="4" literal="RSA_1_5"/>
    <eLiterals name="AES128" value="5" literal="AES128"/>
    <eLiterals name="AES192" value="6" literal="AES192"/>
    <eLiterals name="AES256" value="7" literal="AES256"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncryptionPolicy" eSuperTypes="#//SecurityPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedCipherAlgorithms"
        unique="false" upperBound="-1" eType="#//CipherAlgorithmKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredCipherAlgorithm"
        eType="#//CipherAlgorithmKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encryptedParts" upperBound="-1"
        eType="#//MessagePartRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CipherAlgorithmKind">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="Basic128" value="1" literal="Basic128"/>
    <eLiterals name="Basic192" value="2" literal="Basic192"/>
    <eLiterals name="Basic256" value="3" literal="Basic256"/>
    <eLiterals name="DES" value="4" literal="DES"/>
    <eLiterals name="TRIPLE_DES" value="5" literal="3DES"/>
    <eLiterals name="AES128" value="6" literal="AES128"/>
    <eLiterals name="AES256" value="7" literal="AES256"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuthTokenKind">
    <eLiterals name="UsernamePassword" literal="UsernamePassword"/>
    <eLiterals name="SAML" value="1" literal="SAML"/>
    <eLiterals name="SAML2" value="2" literal="SAML2"/>
    <eLiterals name="Kerberos" value="3" literal="Kerberos"/>
    <eLiterals name="SPNEGO" value="4" literal="SPNEGO"/>
    <eLiterals name="RELToken" value="5" literal="RELToken"/>
    <eLiterals name="X509Certificate" value="6" literal="X509Certificate"/>
    <eLiterals name="OAuth" value="7" literal="OAuth"/>
    <eLiterals name="OAuth2" value="8" literal="OAuth2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogPolicyKind">
    <eLiterals name="none" literal="none"/>
    <eLiterals name="header" value="1" literal="header"/>
    <eLiterals name="all" value="2" literal="all"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="AvailabilityAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="percentile" eType="#//Percentile"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mtbf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mttrPercentile" eType="#//Percentile"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regularDownTimes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LatencyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="percentile" eType="#//Percentile"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReliablityAsserttion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliability" eType="#//ReliablilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inOrderDelivery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReliablilityKind">
    <eLiterals name="EXACTLY_ONCE" literal="exactly-once"/>
    <eLiterals name="AT_MOST_ONCE" value="1" literal="at-most-once"/>
    <eLiterals name="AT_LEAST_ONCE" value="2" literal="at-least-once"/>
    <eLiterals name="BEST_EFFORT" value="3" literal="best-effort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CostAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="costsAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billedUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccuracyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxErrorRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Percentile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndpointQualifierRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointQualifier" eType="ecore:EClass ../../../../../org.fornax.soa.semanticsdsl/src-gen/org/fornax/soa/SemanticsDsl.ecore#//Qualifier"/>
  </eClassifiers>
</ecore:EPackage>
