/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.bindingdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BindingDslUiModule extends org.xkonnex.repo.dsl.bindingdsl.ui.AbstractBindingDslUiModule {
	public BindingDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

/*
	public Class<? extends ISemanticModelTransformer> bindISemanticModelTransformer() {
		return BindingDslTransformer.class;
	}
*/
}
