/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.semanticsdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SemanticsDslUiModule extends org.xkonnex.repo.dsl.semanticsdsl.ui.AbstractSemanticsDslUiModule {
	public SemanticsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
