/*
* generated by Xtext
*/
package org.fornax.soa.profiledsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.fornax.soa.profiledsl.sOAProfileDsl.DataType;
import org.fornax.soa.profiledsl.sOAProfileDsl.MessageHeader;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SOAProfileDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SOAProfileDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
	
	String image (DataType ele) {
		return "full/obj16/datatype_obj.gif";
	}
	
	String image (MessageHeader ele) {
		return "full/obj16/message_part.gif";
	}
}
