/*
* generated by Xtext
*/
package org.fornax.soa.profiledsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.fornax.soa.profiledsl.sOAProfileDsl.DataType;
import org.fornax.soa.profiledsl.sOAProfileDsl.MessageHeader;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SOAProfileDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SOAProfileDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	
	String image (DataType ele) {
		return "full/obj16/datatype_obj.gif";
	}
	
	String image (MessageHeader ele) {
		return "full/obj16/message_part.gif";
	}

	Object text (org.fornax.soa.profiledsl.sOAProfileDsl.Class ele) {
		StyledString name = new StyledString(ele.getName());
		StyledString versionAndState  = new StyledString(" " + ele.getVersion().getVersion() + " " + ele.getState().getName (), StyledString.DECORATIONS_STYLER);
		name.append(versionAndState);
		return name;
	}
	
	String image (org.fornax.soa.profiledsl.sOAProfileDsl.Class ele) {
		return "full/obj16/bo_obj.gif";
	}
	
	Object text (org.fornax.soa.profiledsl.sOAProfileDsl.Enumeration ele) {
		StyledString name = new StyledString(ele.getName());
		StyledString versionAndState  = new StyledString(" " + ele.getVersion().getVersion() + " " + ele.getState().getName (), StyledString.DECORATIONS_STYLER);
		name.append(versionAndState);
		return name;
	}
	String image (org.fornax.soa.profiledsl.sOAProfileDsl.Enumeration ele) {
		return "full/obj16/enum_obj.gif";
	}
}
