/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.sladsl.scoping;

import org.xkonnex.repo.dsl.basedsl.scoping.SOABaseDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class SLADslScopeProvider extends SOABaseDslScopeProvider {

}
