/*
* generated by Xtext
*/
package org.fornax.soa.profiledsl.ui.contentassist;

import org.fornax.soa.profiledsl.ui.contentassist.AbstractSOAProfileDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SOAProfileDslProposalProvider extends AbstractSOAProfileDslProposalProvider {

}
