/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.sladsl.ui

import org.eclipse.ui.plugin.AbstractUIPlugin

/** 
 * Use this class to register components to be used within the IDE.
 */
class SLADslUiModule extends org.xkonnex.repo.dsl.sladsl.ui.AbstractSLADslUiModule {
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
}
