/*
* generated by Xtext
*/
package org.fornax.soa.ui.labeling;

import org.apache.log4j.Logger;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.jface.viewers.StyledString.Styler;
import org.eclipse.swt.graphics.TextStyle;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.fornax.soa.basedsl.sOABaseDsl.Import;
import org.fornax.soa.profiledsl.sOAProfileDsl.LifecycleState;
import org.fornax.soa.profiledsl.scoping.versions.ILifecycleStateResolver;
import org.fornax.soa.serviceDsl.BusinessObject;
import org.fornax.soa.serviceDsl.ComplexConsiderationPropertyRef;
import org.fornax.soa.serviceDsl.ConsiderationParameterRef;
import org.fornax.soa.serviceDsl.DataObjectRef;
import org.fornax.soa.serviceDsl.DataTypeRef;
import org.fornax.soa.serviceDsl.DomainNamespace;
import org.fornax.soa.serviceDsl.EnumTypeRef;
import org.fornax.soa.serviceDsl.Enumeration;
import org.fornax.soa.serviceDsl.ExceptionRef;
import org.fornax.soa.serviceDsl.InternalNamespace;
import org.fornax.soa.serviceDsl.Operation;
import org.fornax.soa.serviceDsl.OperationRef;
import org.fornax.soa.serviceDsl.Parameter;
import org.fornax.soa.serviceDsl.Property;
import org.fornax.soa.serviceDsl.QueryObject;
import org.fornax.soa.serviceDsl.RequiredServiceRef;
import org.fornax.soa.serviceDsl.Service;
import org.fornax.soa.serviceDsl.ServiceRef;
import org.fornax.soa.serviceDsl.SimpleConsiderationPropertyRef;
import org.fornax.soa.serviceDsl.TypeRef;
import org.fornax.soa.serviceDsl.VersionedTypeRef;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class ServiceDslLabelProvider extends DefaultEObjectLabelProvider {
	
	private static Logger _log = Logger.getLogger (ServiceDslLabelProvider.class);
	
	@Inject
	private ILifecycleStateResolver stateResolver;

	private static Styler STRIKETHROUGH = new Styler() {
		@Override
		public void applyStyles(TextStyle textStyle) {
			textStyle.strikeout = true;
		}
	};
	
	@Inject
	public ServiceDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	Object text (Service ele) {
		StyledString name = new StyledString(ele.getName());
		LifecycleState state = stateResolver.getLifecycleState(ele);
		String stateName = state != null ? state.getName () : "";
		StyledString versionAndState  = new StyledString(" " + ele.getVersion().getVersion() + " " + stateName, StyledString.DECORATIONS_STYLER);
		name.append(versionAndState);
		if (ele.isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	String image (Service ele) {
		return "full/obj16/service_obj.gif";
	}
	
	Object text (ServiceRef ele) {
		StyledString name = new StyledString(ele.getService ().getName());
		if (ele.getService().isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	
	String image (ServiceRef ele) {
		return "full/obj16/ServiceRef.gif";
	}
	Object text (RequiredServiceRef ele) {
		StyledString name = new StyledString(ele.getService ().getName());
		if (ele.getService().isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	
	String image (RequiredServiceRef ele) {
		return "full/obj16/ServiceRef.gif";
	}
	
	Object text (BusinessObject ele) {
		StyledString name = new StyledString(ele.getName());
		LifecycleState state = stateResolver.getLifecycleState(ele);
		String stateName = state != null ? state.getName () : "";
		StyledString versionAndState  = new StyledString(" " + ele.getVersion().getVersion() + " " + stateName, StyledString.DECORATIONS_STYLER);
		name.append(versionAndState);
		if (ele.isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	String image (BusinessObject ele) {
		return "full/obj16/bo_obj.gif";
	}
	Object text (QueryObject ele) {
		StyledString name = new StyledString(ele.getName());
		LifecycleState state = stateResolver.getLifecycleState(ele);
		String stateName = state != null ? state.getName () : "";
		StyledString versionAndState  = new StyledString(" " + ele.getVersion().getVersion() + " " + stateName, StyledString.DECORATIONS_STYLER);
		name.append(versionAndState);
		if (ele.isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	String image (QueryObject ele) {
		return "full/obj16/QueryObject.gif";
	}
	
	Object text (Enumeration ele) {
		StyledString name = new StyledString(ele.getName());
		LifecycleState state = stateResolver.getLifecycleState(ele);
		String stateName = state != null ? state.getName () : "";
		StyledString versionAndState  = new StyledString(" " + ele.getVersion().getVersion() + " " + stateName, StyledString.DECORATIONS_STYLER);
		name.append(versionAndState);
		if (ele.isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	String image (Enumeration ele) {
		return "full/obj16/enum_obj.gif";
	}
	
	Object text (org.fornax.soa.serviceDsl.Exception ele) {
		StyledString name = new StyledString(ele.getName());
		LifecycleState state = stateResolver.getLifecycleState(ele);
		String stateName = state != null ? state.getName () : "";
		StyledString versionAndState  = new StyledString(" " + ele.getVersion().getVersion() + " " + stateName, StyledString.DECORATIONS_STYLER);
		name.append(versionAndState);
		if (ele.isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	
	String image (org.fornax.soa.serviceDsl.Exception ele) {
		return "full/obj16/fault.gif";
	}
	
	String image (DomainNamespace ele) {
		return "full/obj16/package_obj.gif";
	}

	String image (InternalNamespace ele) {
		return "full/obj16/packd_obj.gif";
	}
	
	Object text (Operation ele) {
		StyledString name = new StyledString(ele.getName());
		if (ele.isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	Object text (OperationRef ele) {
		StyledString name = new StyledString(ele.getOperation().getName());
		if (ele.getOperation().isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}

	String image (Operation ele) {
		return "full/obj16/methpub_obj.gif";
	}
	
	Object text (Property ele) {
		String name = ele.getName();
		String typeName = getTypeName(ele.getType());
		if (typeName != null) {
			StyledString styledName = new StyledString (name);
			StyledString styledTypeName = new StyledString (" : " + typeName, StyledString.DECORATIONS_STYLER);
			styledName.append(styledTypeName);
			return styledName;
		} else {			
			return ele.getName();
		}
	}
	String image (Property ele) {
		return "full/obj16/field_public_obj.gif";
	}
		
	Object text (Parameter ele) {
		String name = ele.getName();
		String typeName = getTypeName(ele.getType());
		if (typeName != null) {
			StyledString styledName = new StyledString (name);
			StyledString styledTypeName = new StyledString (" : " + typeName, StyledString.DECORATIONS_STYLER);
			styledName.append(styledTypeName);
			return styledName;
		} else {			
			return ele.getName();
		}
	}

	String image (Import ele) {
		return "full/obj16/imp_obj.gif";
	}
	
	String text(ConsiderationParameterRef ele) {
		return ele.getParam().getName();
	}
	
	String text(ComplexConsiderationPropertyRef ele) {
		return ele.getParentProperty().getName();
	}
	
	String text(SimpleConsiderationPropertyRef ele) {
		return ele.getProperty().getName();
	}
	
	Object text(DataObjectRef ele) {
		StyledString name = new StyledString(ele.getType().getName());
		if (ele.getType().isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	Object text(EnumTypeRef ele) {
		StyledString name = new StyledString(ele.getType().getName());
		if (ele.getType().isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	Object text(ExceptionRef ele) {
		StyledString name = new StyledString(ele.getException().getName());
		if (ele.getException().isDeprecated()) {
			name.setStyle(0, name.length(), STRIKETHROUGH);
		}
		return name;
	}
	
	
	private String getTypeName (TypeRef t) {
		if (t instanceof DataTypeRef) {
			DataTypeRef dtRef = (DataTypeRef) t;
			if (dtRef.getType() instanceof org.fornax.soa.profiledsl.sOAProfileDsl.DataType )
				return ((org.fornax.soa.profiledsl.sOAProfileDsl.DataType) dtRef.getType()).getName();
			else
				_log.error("Unexpected reference type " + dtRef.getType().eClass().getName());
		}
		if (t instanceof DataObjectRef)
			return ((DataObjectRef)t).getType().getName();
		if (t instanceof EnumTypeRef)
			return ((EnumTypeRef)t).getType().getName();
		if (t instanceof VersionedTypeRef)
			return ((VersionedTypeRef)t).getType().getName();
		return null;
	}
}
