/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.solutiondsl.serializer;

import org.xkonnex.repo.dsl.solutiondsl.serializer.AbstractSolutionDslSyntacticSequencer;

public class SolutionDslSyntacticSequencer extends AbstractSolutionDslSyntacticSequencer {
}
