/*
 * generated by Xtext
 */
package org.fornax.soa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SolutionDslUiModule extends org.fornax.soa.ui.AbstractSolutionDslUiModule {
	public SolutionDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
