/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.semanticsdsl.serializer;

import org.xkonnex.repo.dsl.semanticsdsl.serializer.AbstractSemanticsDslSemanticSequencer;

public class SemanticsDslSemanticSequencer extends AbstractSemanticsDslSemanticSequencer {
}
