/*
* generated by Xtext
*/
package org.fornax.soa.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.fornax.soa.environmentDsl.AppServer;
import org.fornax.soa.environmentDsl.Database;
import org.fornax.soa.environmentDsl.ESB;
import org.fornax.soa.environmentDsl.EnvImport;
import org.fornax.soa.environmentDsl.Environment;
import org.fornax.soa.environmentDsl.Host;
import org.fornax.soa.environmentDsl.SAP;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class EnvironmentDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public EnvironmentDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/

	String image (EnvImport ele) {
		return "full/obj16/imp_obj.gif";
	}
	
	String image (Environment ele) {
		return "full/obj16/env.gif";
	}
	
	String image (Host ele) {
		return "full/obj16/server.gif";	
	}
	
	String image (AppServer ele) {
		return "full/obj16/servnode.gif";	
	}
	
	String image (ESB ele) {
		return "full/obj16/servnode.gif";	
	}
	
	String image (SAP ele) {
		return "full/obj16/servnode.gif";	
	}
	
	String image (Database ele) {
		return "full/obj16/db.gif";	
	}
}
