/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.basedsl.serializer;

import org.xkonnex.repo.dsl.basedsl.serializer.AbstractSOABaseDslSyntacticSequencer;

public class SOABaseDslSyntacticSequencer extends AbstractSOABaseDslSyntacticSequencer {
}
