/*
 * generated by Xtext
 */
package org.fornax.soa.moduledsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModuleDslUiModule extends org.fornax.soa.moduledsl.ui.AbstractModuleDslUiModule {
	public ModuleDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
