/*
 * generated by Xtext
 */
package org.fornax.soa;

import org.fornax.soa.basedsl.resource.EObjectDescriptionBuilder;
import org.fornax.soa.basedsl.resource.IEObjectDescriptionBuilder;
import org.fornax.soa.basedsl.sOABaseDsl.SOABaseDslFactory;
import org.fornax.soa.basedsl.sOABaseDsl.impl.SOABaseDslFactoryImpl;
import org.fornax.soa.basedsl.scoping.VersionedGlobalScopeProvider;
import org.fornax.soa.basedsl.search.IPredicateSearch;
import org.fornax.soa.basedsl.search.IReferenceSearch;
import org.fornax.soa.basedsl.search.PredicateReferenceSearch;
import org.fornax.soa.basedsl.search.PredicateSearch;
import org.fornax.soa.basedsl.validation.IPluggableValidatorProvider;
import org.fornax.soa.basedsl.validation.ReflectivePluggableValidatorProvider;
import org.fornax.soa.moduledsl.query.DefaultModuleVersionMatcher;
import org.fornax.soa.moduledsl.query.IModuleVersionMatcher;
import org.fornax.soa.profiledsl.scoping.versions.DefaultStateMatcher;
import org.fornax.soa.profiledsl.scoping.versions.DefaultVersionFilterProvider;
import org.fornax.soa.profiledsl.scoping.versions.IStateMatcher;
import org.fornax.soa.profiledsl.scoping.versions.IVersionFilterProvider;
import org.fornax.soa.profiledsl.scoping.versions.LifecycleStateComparator;
import org.fornax.soa.profiledsl.scoping.versions.LifecycleStateResolver;
import org.fornax.soa.profiledsl.scoping.versions.StateAttributeLifecycleStateResolver;
import org.fornax.soa.scoping.IEnvironmentPerspectiveSelector;
import org.fornax.soa.scoping.impl.DefaultEnvironmentPerspectiveSelector;
import org.fornax.soa.util.EnvironmentTypeComparator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BindingDslRuntimeModule extends org.fornax.soa.AbstractBindingDslRuntimeModule {
	
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return VersionedGlobalScopeProvider.class;
	}

	@org.eclipse.xtext.service.SingletonBinding(eager=true)	
	public Class<? extends IPluggableValidatorProvider> bindIPluggableValidatorProvider () {
		return ReflectivePluggableValidatorProvider.class;
	}
	
	public Class<? extends IStateMatcher> bindIStateMatcher () {
		return DefaultStateMatcher.class;
	}
	
	public Class<? extends EnvironmentTypeComparator> bindEnvironmentTypeComparator () {
		return EnvironmentTypeComparator.class;
	}
	
	public Class<? extends LifecycleStateComparator> bindLifecycleStateComparator () {
		return LifecycleStateComparator.class;
	}
	
	public Class<? extends LifecycleStateResolver> bindLifecycleStateResolver () {
		return StateAttributeLifecycleStateResolver.class;
	}
	
	@org.eclipse.xtext.service.SingletonBinding	
	public Class<? extends IEnvironmentPerspectiveSelector> bindIEnvironmentPerspectiveSelector () {
		return DefaultEnvironmentPerspectiveSelector.class;
	}
	
	public Class<? extends IPredicateSearch> bindIPredicateSearch () {
		return PredicateSearch.class;
	}
	
	public Class<? extends IReferenceSearch> bindIReferenceSearch () {
		return PredicateReferenceSearch.class;
	}
	
	public Class<? extends IModuleVersionMatcher> bindIModuleVersionMatcher () {
		return DefaultModuleVersionMatcher.class;
	}

	public Class<? extends SOABaseDslFactory> bindSOABaseDslFactory () {
		return SOABaseDslFactoryImpl.class;
	}
	
	public Class<? extends IEObjectDescriptionBuilder> bindIEObjectDescrionBuilder () {
		return EObjectDescriptionBuilder.class;
	}
	
	@SuppressWarnings("rawtypes")
	public Class<? extends IVersionFilterProvider> bindIVersionFilterProvider () {
		return DefaultVersionFilterProvider.class;
	}

}
