/*
 * generated by Xtext 2.11.0
 */
package org.xkonnex.repo.dsl.semanticsdsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class SemanticsDslWebModule extends AbstractSemanticsDslWebModule {
}
