/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.sladsl.serializer;

import org.xkonnex.repo.dsl.sladsl.serializer.AbstractSLADslSemanticSequencer;

public class SLADslSemanticSequencer extends AbstractSLADslSemanticSequencer {
}
