package org.xkonnex.repo.dsl.servicedsl.validation;

public enum VersionedObjectFeatureConflicts {
	
	NONE,
	NAME_CONFLICT,
	OUT_OF_ORDER_FEATURE,
	WRONG_TYPE,
	WRONG_TYPE_VERSION_RANGE,
	WRONG_MULTIPLICITY,
	MISSING,
	CHANGED_TO_MANDATORY,
	NEW_FEATURE,
	NEW_FEATURE_MANDATORY,
	NEW_FEATURE_IN_WRONG_POSITION,
	NEW_FEATURE_FROM_OTHER_NAMESPACE
}
