/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.moduledsl.serializer;

import org.xkonnex.repo.dsl.moduledsl.serializer.AbstractModuleDslSemanticSequencer;

public class ModuleDslSemanticSequencer extends AbstractModuleDslSemanticSequencer {
}
