/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.moduledsl.serializer;

import org.xkonnex.repo.dsl.moduledsl.serializer.AbstractModuleDslSyntacticSequencer;

public class ModuleDslSyntacticSequencer extends AbstractModuleDslSyntacticSequencer {
}
