/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.basedsl.ui.labeling;

import org.eclipse.xtext.common.types.JvmMember;
import org.eclipse.xtext.common.types.JvmType;
import org.xkonnex.repo.dsl.basedsl.baseDsl.Assignment;
import org.xkonnex.repo.dsl.basedsl.baseDsl.Component;
import org.xkonnex.repo.dsl.basedsl.scoping.ComponentExtensions;

import com.google.inject.Inject;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
public class BaseDslLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {
	
	@Inject
	private ComponentExtensions componentExtensions;

	@Inject
	public BaseDslLabelProvider(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	public String text(Component component) {
		if (component.getName() != null)
			return component.getName();
		JvmType type = componentExtensions.getActualType(component);
		if (type != null) {
			if (type instanceof JvmMember)
				return ((JvmMember) type).getSimpleName();
			return type.getQualifiedName('.');
		}
		return "Component";
	}
	
	public String text(Assignment assignment) {
		return assignment.getFeature().getSimpleName();
	}

}
