/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.profiledsl.ui

import org.eclipse.ui.plugin.AbstractUIPlugin

/** 
 * Use this class to register components to be used within the IDE.
 */
class ProfileDslUiModule extends org.xkonnex.repo.dsl.profiledsl.ui.AbstractProfileDslUiModule {
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
}
