/*
* generated by Xtext
*/
package org.fornax.soa.ui.contentassist;

import org.fornax.soa.ui.contentassist.AbstractSLADslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SLADslProposalProvider extends AbstractSLADslProposalProvider {

}
