/*
* generated by Xtext
*/
package org.fornax.soa.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.fornax.soa.bindingDsl.BindingProtocol;
import org.fornax.soa.bindingDsl.DomainBinding;
import org.fornax.soa.bindingDsl.EJB;
import org.fornax.soa.bindingDsl.SAP;
import org.fornax.soa.bindingDsl.SOAP;
import org.fornax.soa.bindingDsl.ServiceBinding;
import org.fornax.soa.environmentDsl.Environment;
import org.fornax.soa.environmentDsl.Server;
import org.fornax.soa.sLADsl.SLA;
import org.fornax.soa.serviceDsl.DomainNamespace;
import org.fornax.soa.basedsl.sOABaseDsl.LowerBoundRangeVersionRef;
import org.fornax.soa.basedsl.sOABaseDsl.MajorVersionRef;
import org.fornax.soa.basedsl.sOABaseDsl.MaxVersionRef;
import org.fornax.soa.basedsl.sOABaseDsl.MinVersionRef;
import org.fornax.soa.serviceDsl.SubNamespace;
import org.fornax.soa.basedsl.sOABaseDsl.VersionRef;
import org.fornax.soa.util.BindingDslHelper;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class BindingDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public BindingDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
	
	String image (DomainBinding ele) {
		return "full/obj16/messageexchange.gif";
	}
	
	String text (DomainBinding ele) {
		return ele.getSubNamespace().getName() + " -> " + ele.getEnvironment().getName();
	}
	
	String text (ServiceBinding ele) {
		return ele.getService().getService().getName() + " " + getVersion(ele.getService().getVersionRef());
	}
	
	String text (org.fornax.soa.sLADsl.SLA ele) {
		return "SLA " + ele.getName();
	}
	
	String text (SOAP ele) {
		Server server = null;
		SubNamespace ns = BindingDslHelper.getSubNamespace(ele);
		if (ele.getProvider() != null)
			server = ele.getProvider().getProvServer();
		if (server == null && ele.getPublisher() != null)
			server = ele.getPublisher().getPubServer();
		if (server == null) {
			Environment env = BindingDslHelper.getEnvironment(ele);
			if (ns instanceof DomainNamespace)
				server = env.getDefaultESB();
			else 
				server = env.getDefaultAppServer();
		}
		if (server != null)
			return "SOAP -> "+server.getName();
		else
			return "SOAP";
	}
	
	String text (SAP ele) {
		String clientText = null;
		if (ele.getClient() != null) {
			org.fornax.soa.environmentDsl.SAP sapServer = (org.fornax.soa.environmentDsl.SAP) ele.getClient().eContainer();
			clientText = sapServer.getName() + ele.getClient().getClient();
		}
		if (clientText != null)
			return "SAP -> " + clientText;
		else
			return "SAP";
	}
	
	String text (EJB ele) {
		Server server = null;
		StringBuffer label = new StringBuffer("EJB");
		SubNamespace ns = BindingDslHelper.getSubNamespace(ele);
		if (ele.getProvider() != null)
			server = ele.getProvider().getProvServer();
		if (server == null && ele.getPublisher() != null)
			server = ele.getPublisher().getPubServer();
		if (server == null) {
			Environment env = BindingDslHelper.getEnvironment(ele);
			if (ns instanceof DomainNamespace)
				server = env.getDefaultESB();
			else 
				server = env.getDefaultAppServer();
		}
		if (server != null)
			label.append(" -> " + server.getName());
		if (ele.getJndiName() != null) {
			String[] jndiNameParts = ele.getJndiName().split("/");
			if (jndiNameParts.length > 0) 
				label.append("/" + jndiNameParts[jndiNameParts.length-1]);
		}
		return label.toString();
	}
	
	private String getVersion (VersionRef verRef) {
		if (verRef instanceof MajorVersionRef)
			return "" + ((MajorVersionRef)verRef).getMajorVersion();
		if (verRef instanceof MaxVersionRef)
			return "<" + ((MaxVersionRef)verRef).getMaxVersion();
		if (verRef instanceof MinVersionRef)
			return ">=" + ((MinVersionRef)verRef).getMinVersion();
		if (verRef instanceof LowerBoundRangeVersionRef) {
			LowerBoundRangeVersionRef ref = (LowerBoundRangeVersionRef)verRef;
			return (ref.getMinVersion() +".."+ref.getMaxVersion());
		}
		return "";
	}
	

	
	String image (ServiceBinding ele) {
		return "full/obj16/invoke.gif";
	}

	String image (BindingProtocol ele) {
		return "full/obj16/message_part.gif";
	}
	
	String image (SOAP ele) {
		return "full/obj16/message_part.gif";
	}
	
	String image (SAP ele) {
		return "full/obj16/message_part.gif";
	}

}
