<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sLADsl"
    nsURI="http://www.fornax.org/soa/SLADsl" nsPrefix="sLADsl">
  <eClassifiers xsi:type="ecore:EClass" name="SlaModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agreements" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//SLA"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SLA">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveUntil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceQualityProperties"
        upperBound="-1" eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//ServiceQualityProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preaple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSecProtClause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restrictions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priorities" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//PriorityDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="escalationProcedure" eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Escalation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalServices" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parties" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Party"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cancellation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraordinaryCancellation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="costs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effortAccounting" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reports" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Report"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" unique="false" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.semanticsdsl/src-gen/org/fornax/soa/SemanticsDsl.ecore#//Tag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import"/>
  <eClassifiers xsi:type="ecore:EClass" name="NsImport" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceQualityProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="escalation" eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Escalation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="penalty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Availability" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//ServiceQualityProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Throughput" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//ServiceQualityProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Latency" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//ServiceQualityProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Maintenance" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//ServiceQualityProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaxDownTime" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//ServiceQualityProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="PriorityDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Escalation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="escalationTargets" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Contact"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procedure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Party">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representatives" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Repesentative"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibilities" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Responsibility"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomerParty" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Party"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProviderParty" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Party"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThirdParty" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Party">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repesentative">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Responsibility">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="escalations" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Escalation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="penalty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleResponsibility" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Responsibility">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Report">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportingResponsibility" eSuperTypes="platform:/resource/org.fornax.soa.sladsl/src-gen/org/fornax/soa/SLADsl.ecore#//Responsibility">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
