/*
 * generated by Xtext
 */
package org.fornax.soa.basedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SOABaseDslUiModule extends org.fornax.soa.basedsl.ui.AbstractSOABaseDslUiModule {
	public SOABaseDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
