/*
* generated by Xtext
*/
package org.xkonnex.repo.dsl.solutiondsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.xkonnex.repo.dsl.servicedsl.serviceDsl.Aggregate;
import org.xkonnex.repo.dsl.servicedsl.serviceDsl.Resource;
import org.xkonnex.repo.dsl.servicedsl.serviceDsl.Service;
import org.xkonnex.repo.dsl.solutiondsl.solutionDsl.InterfaceRef;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SolutionDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SolutionDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	Object text (InterfaceRef ele) {
		if (ele.getInterface () instanceof Service) {
			Service service = (Service)ele.getInterface ();
			StyledString name = new StyledString(service.getName());
			return name;
		}
		if (ele.getInterface () instanceof Resource) {
			Resource resource = (Resource)ele.getInterface ();
			StyledString name = new StyledString(resource.getName());
			return name;
		}
		if (ele.getInterface () instanceof Aggregate) {
			Aggregate aggregate = (Aggregate)ele.getInterface ();
			StyledString name = new StyledString(aggregate.getName());
			return name;
		}
		return "";
	}
	
	String image (InterfaceRef ele) {
		return "full/obj16/ServiceRef.gif";
	}

}
