package org.fornax.soa.validation;

public enum PropertyVersionConflicts {
	
	NONE,
	NAME_CONFLICT,
	OUT_OF_ORDER_ATTRIBUTE,
	WRONG_TYPE,
	WRONG_MULTIPLICITY,
	MISSING,
	CHANGED_TO_MANDATORY,
	MANDATORY_NEW_PROPERTY,
	NEW_PROPERTY_IN_WRONG_POSITION,
	NEW_PROPERTY_FROM_OTHER_NAMESPACE
}
