/*
* generated by Xtext
*/
package org.fornax.soa.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.fornax.soa.solutionDsl.ServiceRef;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SolutionDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SolutionDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	Object text (ServiceRef ele) {
		StyledString name = new StyledString(ele.getService ().getName());
		return name;
	}
	
	String image (ServiceRef ele) {
		return "full/obj16/ServiceRef.gif";
	}

}
