/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.environmentdsl.serializer;

import org.xkonnex.repo.dsl.environmentdsl.serializer.AbstractEnvironmentDslSemanticSequencer;

public class EnvironmentDslSemanticSequencer extends AbstractEnvironmentDslSemanticSequencer {
}
