/*
* generated by Xtext
*/
package org.xkonnex.repo.dsl.sladsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SLADslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
