/*
* generated by Xtext
*/
package org.xkonnex.repo.dsl.semanticsdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SemanticsDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
