/*
 * generated by Xtext 2.9.1
 */
package org.xkonnex.repo.dsl.basedsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xkonnex.repo.dsl.basedsl.baseDsl.Import

@RunWith(XtextRunner)
@InjectWith(BaseDslInjectorProvider)
class BaseDslParsingTest{

	@Inject
	ParseHelper<Import> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			version 1.0
		''')
		Assert.assertNotNull(result)
	}

}
