/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.servicedsl.serializer;

import org.xkonnex.repo.dsl.servicedsl.serializer.AbstractServiceDslSyntacticSequencer;

public class ServiceDslSyntacticSequencer extends AbstractServiceDslSyntacticSequencer {
}
