/*
* generated by Xtext
*/
package org.xkonnex.repo.dsl.sladsl.ui.contentassist;

import org.xkonnex.repo.dsl.sladsl.ui.contentassist.AbstractSLADslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SLADslProposalProvider extends AbstractSLADslProposalProvider {

}
