/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.businessdsl.serializer;

import org.xkonnex.repo.dsl.businessdsl.serializer.AbstractBusinessDslSyntacticSequencer;

public class BusinessDslSyntacticSequencer extends AbstractBusinessDslSyntacticSequencer {
}
