/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.businessdsl.serializer;

import org.xkonnex.repo.dsl.businessdsl.serializer.AbstractBusinessDslSemanticSequencer;

public class BusinessDslSemanticSequencer extends AbstractBusinessDslSemanticSequencer {
}
