package org.xkonnex.repo.dsl.basedsl.version;

public enum VersionClassifier {
	MILESTONE_SNAPSHOT,
	MILESTONE,
	APLHA_SNAPSHOT,
	APLHA,
	BETA_SNAPSHOT,
	BETA,
	RELEASE_CANDITATE_SNAPSHOT,
	RELEASE_CANDITATE,
	FINAL_SNAPSHOT,
	FINAL
}
