/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.profiledsl.serializer;

import org.xkonnex.repo.dsl.profiledsl.serializer.AbstractProfileDslSemanticSequencer;

public class ProfileDslSemanticSequencer extends AbstractProfileDslSemanticSequencer {
}
