/*
 * generated by Xtext
 */
package org.fornax.soa.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class EnvironmentDslScopeProvider extends ImportedNamespaceAwareLocalScopeProvider {

}
