/*
 * generated by Xtext
 */
package org.fornax.soa.formatting;

import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.util.Pair;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class ServiceDslFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		org.fornax.soa.services.ServiceDslGrammarAccess f = (org.fornax.soa.services.ServiceDslGrammarAccess) getGrammarAccess();

		c.setAutoLinewrap(120);
		c.setLinewrap(1, 1, 2).before(f.getSL_COMMENTRule());
		c.setLinewrap(1, 1, 2).before(f.getML_COMMENTRule());
		c.setLinewrap(1, 1, 1).after(f.getML_COMMENTRule());
		c.setLinewrap(1, 2, 2).after(f.getBusinessObjectRule());
		c.setLinewrap(1, 2, 2).after(f.getServiceRule());
		c.setLinewrap(1, 2, 2).after(f.getExceptionRule());
		c.setLinewrap(1, 1, 1).after(f.getPropertyRule());
		c.setLinewrap(1, 2, 1).after(f.getServiceRule());
		c.setLinewrap(2).after(f.getServiceModelAccess().getImportsAssignment_0());
		c.setLinewrap().after(f.getExceptionAccess().getDocAssignment_0());
		c.setLinewrap().after(f.getEnumerationAccess().getDocAssignment_0());
		c.setLinewrap().after(f.getBusinessObjectAccess().getDocAssignment_0());
		c.setLinewrap().after(f.getServiceAccess().getDocAssignment_0());
		c.setLinewrap().after(f.getOperationAccess().getDocAssignment_0());
		c.setLinewrap().after(f.getReferenceAccess().getDocAssignment_0());
		c.setLinewrap().after(f.getAttributeAccess().getDocAssignment_0());
		for (Pair<Keyword, Keyword> pair : f.findKeywordPairs("{", "}")) {
			c.setIndentationIncrement().after(pair.getFirst());
			c.setLinewrap(1).after(pair.getFirst());
			c.setLinewrap(1).after(pair.getSecond());
			c.setIndentationDecrement().before(pair.getSecond());
		}
		for (Keyword kw : f.findKeywords(";")) {
			c.setLinewrap(1).after(kw);
		}
		for (Keyword throwsKw : f.findKeywords("throws")) {
			c.setLinewrap(1).before(throwsKw);
		}
		for (Keyword returnsKw : f.findKeywords("returns")) {
			c.setLinewrap(1).before(returnsKw);
		}
		c.setIndentationIncrement().before(f.getOperationAccess().getReturnAssignment_8_1());
		c.setIndentationDecrement().after(f.getOperationAccess().getReturnAssignment_8_1());
		c.setIndentationIncrement().before(f.getOperationAccess().getThrowsAssignment_9_1());
		c.setIndentationDecrement().after(f.getOperationAccess().getThrowsAssignment_9_1());
	}
}
