/*
 * generated by Xtext 2.9.1
 */
package org.xkonnex.repo.dsl.moduledsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xkonnex.repo.dsl.moduledsl.moduleDsl.ModuleModel

@RunWith(XtextRunner)
@InjectWith(ModuleDslInjectorProvider)
class ModuleDslParsingTest{

	@Inject
	ParseHelper<ModuleModel> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			import SampleArchitectureProfile.ExSOALifecycle.*
			
			import org.example.sales.*
			
			/* A module for services of the sales domain */
			module org.example.sales.esb {
				version 1.0
				lifecycle-state productive
				/* It is bundled as an SCA ESB module */
				assembly-type SCA-Composite
				/*
				 * Two services are provided by the module and we know exactly their versions
				 */
				provides {
					service CustomerManagerBAS fixedVersion 1.0
				}
			}
		''')
		Assert.assertNotNull(result)
	}

}
