/*
 * generated by Xtext
 */
package org.xkonnex.repo.dsl.bindingdsl.ui.labeling

//import org.eclipse.xtext.resource.IEObjectDescription

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
class BindingDslDescriptionLabelProvider extends org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider {

	// Labels and icons can be computed like this:
	
}
